/* ================= ΚΤΗΝΟΤΡΟΦΟΣ ΤΝ — ΒΙΝΤΕΟ ΕΡΓΑΣΙΩΝ =================
   Φορτώνουν ΜΟΝΟ με κλικ, από youtube-nocookie.com (αυξημένη ιδιωτικότητα).
   id: YouTube ID (ελεγμένο με oEmbed) · t: ελληνική περιγραφή · ch: κανάλι · l: γλώσσα (el/en)
   g: ομάδες ζώων ή ["all"] · kw: λέξεις-κλειδιά εργασίας (σύνδεση με Πρόγραμμα ΤΝ & Εργαλεία) */
window.VIDEO_CATS = {care:"✂️ Περιποίηση & σήμανση",health:"💉 Υγεία & θεραπεία",milk:"🥛 Άμελξη",birth:"🍼 Τοκετός & νεογέννητα",repro:"🤰 Αναπαραγωγή",feed:"🌾 Διατροφή & χορτονομή",handle:"🚧 Χειρισμός & περίφραξη",poultry:"🐣 Πουλερικά",bees:"🐝 Μελισσοκομία",species:"🐾 Εκτροφή ειδών"};
window.VIDEOS = [
  // Περιποίηση & σήμανση
  {id:"uoI8F6gmdmg",c:"care",t:"Παραδοσιακός & μηχανικός τρόπος κουρέματος προβάτων",ch:"Thanasis Katopodis",l:"el",g:["smallrum"],kw:["κούρεμα"]},
  {id:"vIOJJIAyRnY",c:"care",t:"Κουρευτική μηχανή προβάτων: ρύθμιση & λίπανση",ch:"VlachosTools",l:"el",g:["smallrum"],kw:["κούρεμα"]},
  {id:"3TqV7JDOGPY",c:"care",t:"Περιποίηση οπλών αιγοπροβάτων για αρχάριους",ch:"NC State Extension",l:"en",g:["smallrum"],kw:["οπλ","νυχ","χωλότ","σήψη"]},
  {id:"pUA_ehSw1yc",c:"care",t:"Κοπή νυχιών αγελάδας — ολλανδική μέθοδος (5 βήματα)",ch:"Irish Farmers Journal",l:"en",g:["cattle"],kw:["οπλ","νυχ","χωλότ"]},
  {id:"VklHIlJ81-A",c:"care",t:"Αντιμετώπιση χωλότητας με ποδόλουτρο",ch:"Teagasc",l:"en",g:["smallrum","cattle"],kw:["ποδόλουτρ","σήψη","οπλ","χωλότ"]},
  {id:"xQq1BhGelDc",c:"care",t:"Τοποθέτηση ενωτίων σε πρόβατα",ch:"CanSheepFed",l:"en",g:["smallrum"],kw:["σήμανση","ενώτι"]},
  {id:"PDadfJMnj24",c:"care",t:"Τοποθέτηση ενωτίων σε μοσχάρια",ch:"Shearwell Data",l:"en",g:["cattle"],kw:["σήμανση","ενώτι"]},
  {id:"9jV74vgYv2w",c:"care",t:"Κούρεμα αλπακά από την αρχή ως το τέλος",ch:"Adam Riley",l:"en",g:["other"],kw:["κούρεμα"]},
  {id:"kDCdzWOzPKs",c:"care",t:"Περιποίηση μακριών οπλών αλόγου",ch:"Idaho Horseshoeing School",l:"en",g:["equine"],kw:["πεταλ","οπλ"]},
  // Υγεία & θεραπεία
  {id:"bpiPDjBzvMc",c:"health",t:"Εμβόλια προβάτων — εμπειρία κτηνοτρόφου",ch:"Η Φάρμα της Γιαγιάς",l:"el",g:["smallrum"],kw:["εμβολ","κλωστηρ"]},
  {id:"94P_JEQDobg",c:"health",t:"Υποδόρια ένεση σε αιγοπρόβατα (σωστή τεχνική)",ch:"Tri-State Veterinary Service",l:"en",g:["smallrum","other"],kw:["εμβολ","ένεση","κλωστηρ"]},
  {id:"TWKcDJ0on9Y",c:"health",t:"Χειρισμός & ενέσεις σε χοιρίδια (σίδηρος)",ch:"Michigan Pork Producers",l:"en",g:["pig"],kw:["σίδηρ","ένεση","χοιρίδ"]},
  {id:"m0TFBU75DiM",c:"health",t:"Σωστή τεχνική χορήγησης ανθελμινθικού (drench)",ch:"AHDB Beef & Lamb",l:"en",g:["smallrum","cattle","game","other"],kw:["αποπαρασ","ανθελμ"]},
  {id:"KYFUAvFQ15g",c:"health",t:"Παράσιτα αιγών: βαθμολόγηση FAMACHA",ch:"Oklahoma State Extension",l:"en",g:["smallrum","other","game"],kw:["famacha","αναιμ","αποπαρασ"]},
  {id:"aGj4L75lp5U",c:"health",t:"Κοπρανοσκόπηση — μέτρηση αυγών παρασίτων",ch:"N.C. Cooperative Extension",l:"en",g:["smallrum","cattle","equine","other","game"],kw:["κοπρανοσκόπ","αποπαρασ"]},
  {id:"xnDxJpIb5oo",c:"health",t:"Βαθμολόγηση σωματικής κατάστασης (BCS) προβάτων",ch:"UConn Extension",l:"en",g:["smallrum"],kw:["σωματικ","bcs","flushing","τοξαιμ"]},
  {id:"wASXNn_CTCU",c:"health",t:"Βαθμολόγηση σωματικής κατάστασης αγελάδων",ch:"Penn State Extension",l:"en",g:["cattle"],kw:["σωματικ","bcs","ξήρανση","μετάβασ"]},
  {id:"7WtMTV-rjlQ",c:"health",t:"Τεστ μαστίτιδας CMT σε αγελάδες",ch:"Penn State Extension",l:"en",g:["cattle","smallrum"],kw:["μαστίτ","cmt","ξήρανση"]},
  {id:"K0ngaaHYET4",c:"health",t:"Τυμπανισμός αρνιών — τι είναι στην πραγματικότητα (κτηνίατρος)",ch:"Sez the Vet",l:"en",g:["smallrum","cattle"],kw:["τυμπαν"]},
  // Άμελξη
  {id:"H729x8mPmpU",c:"milk",t:"Πρόβατα φυλής Χίου στο αμελκτήριο",ch:"Ioannis Giannopoulos",l:"el",g:["smallrum"],kw:["άμελξ","γάλα"]},
  {id:"MB9xhbNl-f4",c:"milk",t:"Αρμεγή & γαλακτομέτρηση προβάτων Ασσάφ",ch:"Farma Hellas Genetics",l:"el",g:["smallrum"],kw:["άμελξ","γάλα"]},
  {id:"MXmgzLfUtUI",c:"milk",t:"Περιστροφικό αμελκτήριο αγελάδων",ch:"Πανκτηνοτροφική",l:"el",g:["cattle"],kw:["άμελξ","γάλα"]},
  {id:"XWW-Pwe8Ac4",c:"milk",t:"Καλή πρακτική άμελξης — εμβάπτιση θηλών",ch:"Interactive Content",l:"en",g:["cattle","smallrum"],kw:["άμελξ","μαστίτ"]},
  // Τοκετός & νεογέννητα
  {id:"XsAcoGzUt5Q",c:"birth",t:"Προετοιμασία των μοσχίδων για τον τοκετό",ch:"EURCAW Ruminants & Equines",l:"el",g:["cattle"],kw:["τοκετ","μετάβασ","close-up","ξήρανση"]},
  {id:"Yh6o2Fu4SqE",c:"birth",t:"Πότε & πώς επεμβαίνουμε σε δύσκολο τοκετό αγελάδας",ch:"Beef Cattle Research Council",l:"en",g:["cattle"],kw:["τοκετ","δυστοκ"]},
  {id:"vJRDvhb8QUQ",c:"birth",t:"Σωστή τοποθέτηση αλυσίδων τοκετού",ch:"Progressive Dairy",l:"en",g:["cattle"],kw:["τοκετ","δυστοκ"]},
  {id:"Sbnwn3ODrkU",c:"birth",t:"Βοήθεια σε τοκετό προβατίνας — τα βασικά",ch:"Shropshire Farm Vets",l:"en",g:["smallrum"],kw:["τοκετ","δυστοκ","γέννα"]},
  {id:"VI4aTgt8q2s",c:"birth",t:"Ορθές πρακτικές χορήγησης πρωτογάλακτος στα νεογέννητα αρνιά",ch:"Innovation and Impact Hub",l:"el",g:["smallrum"],kw:["πρωτόγαλ","νεογέν","τοκετ"]},
  {id:"XQfSWLBIegw",c:"birth",t:"Τεχνητός θηλασμός & επιτυχημένη ανάπτυξη αρνιών",ch:"Innovation and Impact Hub",l:"el",g:["smallrum"],kw:["θηλασ","απογαλ","τεχνητ"]},
  {id:"P7PUU1eLZIQ",c:"birth",t:"Τάισμα αρνιών/κατσικιών με οισοφαγικό σωλήνα",ch:"Purdue Extension",l:"en",g:["smallrum"],kw:["πρωτόγαλ","οισοφαγ","νεογέν"]},
  {id:"t7LfOyU6BSA",c:"birth",t:"Κοπή ουράς αρνιών με ελαστικό δακτύλιο (καλή πρακτική)",ch:"Animal Health Australia",l:"en",g:["smallrum"],kw:["ευνουχ","ουρ","δακτύλ"]},
  // Αναπαραγωγή
  {id:"gVdqsXCYKBM",c:"repro",t:"Διαχείριση αιγοπροβάτων την εποχή του ζευγαρώματος",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["smallrum"],kw:["οχεία","flushing","κριαρ","τράγ"]},
  {id:"uBctCa7nLnw",c:"repro",t:"Συγχρονισμός προβάτων για σπερματέγχυση",ch:"MANTIS Farm management",l:"el",g:["smallrum"],kw:["συγχρον","σπόγγ","οχεία","οίστρ"]},
  {id:"h69GQPQXXBE",c:"repro",t:"Τεχνητή σπερματέγχυση προβάτου",ch:"MANTIS Farm management",l:"el",g:["smallrum"],kw:["σπερματέγχ"]},
  {id:"stvnGYcKz60",c:"repro",t:"Τεχνητή σπερματέγχυση βοοειδών",ch:"SUNUP TV (Oklahoma State)",l:"en",g:["cattle"],kw:["σπερματέγχ","οίστρ"]},
  {id:"VZFTmPlzuWo",c:"repro",t:"Υπερηχογράφημα κυοφορίας προβάτων",ch:"Texas A&M Sheep and Goats",l:"en",g:["smallrum"],kw:["κυοφορ","διάγνωση","υπέρηχ"]},
  {id:"u15UbhJtsKA",c:"repro",t:"Πώς φοράμε το σαμάρι σημαδέματος στο κριάρι",ch:"NETTEX",l:"en",g:["smallrum"],kw:["οχεία","κριαρ","σημάδ"]},
  // Διατροφή & χορτονομή
  {id:"nphZ2P1yivs",c:"feed",t:"Ολικό σιτηρέσιο (TMR) σε πρόβατα Ασσάφ",ch:"Pimenas",l:"el",g:["smallrum"],kw:["σιτηρέσ","tmr","ζωοτροφ","διατροφ"]},
  {id:"WNYU34eUu24",c:"feed",t:"Αναμικτήρες TMR: σύγκριση τύπων",ch:"KUHN",l:"en",g:["cattle","smallrum"],kw:["σιτηρέσ","tmr","ζωοτροφ"]},
  {id:"v4zHpdszJiI",c:"feed",t:"Ενσίρωση καλαμποκιού σε σάκο",ch:"MANTIS Farm management",l:"el",g:["cattle","smallrum"],kw:["ενσίρωμα","ενσίρωση"]},
  {id:"JkXm6RNtOsg",c:"feed",t:"Συγκομιδή τριφυλλιού: κόψιμο, γύρισμα, δέσιμο",ch:"Xristos Katsoulas",l:"el",g:["cattle","smallrum","equine"],kw:["χορτονομ","σανός","τριφύλλ"]},
  // Χειρισμός & περίφραξη
  {id:"J3ed7U5SRrA",c:"handle",t:"Εγκαταστάσεις & χειρισμός μικρού κοπαδιού προβάτων",ch:"OSU Extension",l:"en",g:["smallrum"],kw:["χειρισμ","διαλογ"]},
  {id:"BWGksusrdHs",c:"handle",t:"Εκτίμηση βάρους βοοειδών με μετροταινία",ch:"Purdue Extension",l:"en",g:["cattle"],kw:["βάρος","ζύγ"]},
  {id:"uTimrjgDa80",c:"handle",t:"Ηλεκτρική περίφραξη — πώς να την κάνουμε",ch:"Το Κανάλι του Γιάννη",l:"el",g:["all"],kw:["περίφραξ","βοσκ"]},
  {id:"hVmqE0tcV1Y",c:"handle",t:"Εντολές ποιμενικού σκύλου εξηγημένες",ch:"Seanthesheepman",l:"en",g:["dogs","smallrum"],kw:["σκύλ","βοσκ"]},
  // Πουλερικά
  {id:"7Zxl3jJjGlQ",c:"poultry",t:"Πώς να μεγαλώσετε κότες",ch:"Wikifarmer",l:"el",g:["poultry"],kw:["κοτέτσ","ωοτοκ","αυγ","φωτισμ"]},
  {id:"IRTf__2M7qg",c:"poultry",t:"Εκκόλαψη: πώς βγαίνει το κοτοπουλάκι στην κλωσσομηχανή",ch:"Farma Jim Cott",l:"el",g:["poultry"],kw:["επώαση","εκκόλαψ"]},
  {id:"LLdKVwSfcpc",c:"poultry",t:"Ωοσκόπηση αυγών",ch:"Farma Jim Cott",l:"el",g:["poultry"],kw:["ωοσκόπ","επώαση"]},
  {id:"NmvExuW2cM8",c:"poultry",t:"Θερμοκρασία κλωσσομητέρας & συμπεριφορά νεοσσών",ch:"Poulin Grain",l:"en",g:["poultry"],kw:["κλωσσομ","νεοσσ","θερμοκρασία θαλάμου"]},
  // Μελισσοκομία
  {id:"iF4yDHvj2eU",c:"bees",t:"Επιθεώρηση κυψέλης, αφεσμού & παραφυάδας",ch:"Μέλι Λεωνίδας",l:"el",g:["bees"],kw:["κυψέλ","σμηνουργ","παραφυάδ"]},
  {id:"cJZ1wc6Zwh0",c:"bees",t:"Σωστή τεχνική επιθεώρησης κυψέλης",ch:"UF Honey Bee Lab",l:"en",g:["bees"],kw:["κυψέλ","σμηνουργ"]},
  {id:"b8quxrkazSU",c:"bees",t:"Τρύγος μελιού στη Σίφνο",ch:"KAIPOUTHEOS.GR",l:"el",g:["bees"],kw:["τρύγ","μέλι"]},
  {id:"1iqfW_0EHVw",c:"bees",t:"Ξεκαπάκωμα κηρήθρας με ζεστό μαχαίρι",ch:"MahakoBees",l:"en",g:["bees"],kw:["τρύγ","ξεκαπάκ"]},
  {id:"3iQmbGNRO1w",c:"bees",t:"Θεραπεία βαρρόα με ενστάλαξη οξαλικού οξέος",ch:"To Kofini",l:"el",g:["bees"],kw:["βαρρόα","οξαλικ"]},
  {id:"k95CrnTSTCY",c:"bees",t:"Μέτρηση βαρρόα με πλύση αλκοόλης",ch:"University of Guelph",l:"en",g:["bees"],kw:["βαρρόα"]},
  // Εκτροφή ειδών
  {id:"-Gw-tScsU0U",c:"species",t:"Πώς γίνεται η εκτροφή σαλιγκαριών στην Ελλάδα",ch:"24h Online",l:"el",g:["snails"],kw:["σαλιγκ","πάρκ"]},
  {id:"UAIQszb7llU",c:"species",t:"Εκτροφή σαλιγκαριών",ch:"bioprasino.gr",l:"el",g:["snails"],kw:["σαλιγκ"]},
  {id:"12l15vLo_gk",c:"species",t:"Ιχθυοκαλλιέργεια πέστροφας — Άγκιστρο Σερρών",ch:"AGKISTRO ONLINE",l:"el",g:["fish"],kw:["πέστροφ","δεξαμεν"]},
  {id:"EUdUOF-Elm8",c:"species",t:"Πώς λειτουργεί μια σύγχρονη μονάδα πέστροφας",ch:"Aquaculture Tribe",l:"en",g:["fish"],kw:["πέστροφ","οξυγόν"]},
  {id:"XpHBWzhw5ec",c:"species",t:"Από τον μεταξοσκώληκα στο μετάξι — σηροτροφία στο Σουφλί",ch:"Smart Crochet",l:"el",g:["insects"],kw:["μεταξοσκ","κουκούλ"]},
  {id:"SFmwujBWBj4",c:"species",t:"Πώς εκτρέφουμε μεταξοσκώληκες",ch:"The More You Grow",l:"en",g:["insects"],kw:["μεταξοσκ"]},
  {id:"SbzedftrQJw",c:"species",t:"Μονάδα μαύρης στρατιωτικής μύγας (BSF)",ch:"Gardening Australia",l:"en",g:["insects"],kw:["bsf","έντομ","υπόστρωμ"]},
  {id:"GZU8Z5zlbZk",c:"species",t:"3 βασικά πράγματα στην εκτροφή κουνελιών",ch:"Φάρμα «Η Ράχη»",l:"el",g:["rabbit"],kw:["κουνέλ"]},
  {id:"MHdWsMdVMDA",c:"species",t:"Συζήτηση για τη χοιροτροφία",ch:"Σχολή Κρέατος",l:"el",g:["pig"],kw:["χοιρ"]},
  {id:"O4l0S0-1O4Y",c:"species",t:"Ελληνικός Ποιμενικός Σκύλος",ch:"Billy's Traffic TV (ΑΓΡΟweek)",l:"el",g:["dogs"],kw:["σκύλ","ποιμενικ"]},
  {id:"c7or0y2towI",c:"species",t:"Σκύλοι φύλακες προστατεύουν το κοπάδι από λύκους",ch:"BBC Earth",l:"en",g:["dogs","smallrum"],kw:["σκύλ","θηρευτ"]},
  {id:"3mWlTTDUHYY",c:"species",t:"Πώς να εκτρέψετε φασιανούς",ch:"Rambo Outfitters",l:"en",g:["poultry"],kw:["φασιαν"]},
  {id:"WuBEcjQ_2tk",c:"species",t:"Περιστέρια κρεατοπαραγωγής (πιτσούνια)",ch:"Sarah Chrisman",l:"en",g:["poultry"],kw:["περιστ","πιτσούν"]},
  {id:"e4vtz6dJR4U",c:"species",t:"Εκτροφή στρουθοκαμήλων — επίσκεψη σε φάρμα",ch:"Iowa PBS",l:"en",g:["poultry"],kw:["στρουθοκ"]},
  {id:"1T4QHdB8LK4",c:"species",t:"Μεγάλη μονάδα ελαφοτροφίας",ch:"Deer Farming Channel",l:"en",g:["game"],kw:["ελάφ","βαρβατίλ"]}
];

/* ================= ΠΕΡΙΣΣΟΤΕΡΑ ΕΛΛΗΝΙΚΑ ΒΙΝΤΕΟ (v1.5) ================= */
window.VIDEO_CATS.dairy="🧀 Γάλα & τυροκόμηση";
window.VIDEOS.push(
  // Περιποίηση
  {id:"dS2UWpAp7cA",c:"care",t:"Πώς κόβουμε σωστά τα νύχια στα πρόβατα",ch:"Farma Aggelopoulos",l:"el",g:["smallrum"],kw:["οπλ","νυχ","χωλότ","σήψη"]},
  {id:"CR_g1l_Nohg",c:"care",t:"Η κουρά των προβάτων στα Μητάτα",ch:"Eleni Lazarou",l:"el",g:["smallrum"],kw:["κούρεμα"]},
  // Υγεία
  {id:"ClL88f6FKB0",c:"health",t:"Έλεγχος υποκλινικής μαστίτιδας με CMT",ch:"PROUD Farm Incubator",l:"el",g:["cattle","smallrum"],kw:["μαστίτ","cmt","ξήρανση"]},
  {id:"iu05gtuh4O4",c:"health",t:"Ενημέρωση για τη νόσο «Ευλογιά των αιγοπροβάτων»",ch:"Περιφέρεια Στερεάς Ελλάδας",l:"el",g:["smallrum"],kw:["ευλογι","επαγρύπνηση","βιοασφάλ"]},
  {id:"6UJdRI5WQsM",c:"health",t:"Ευλογιά προβάτων: συμπτώματα & τι κάνει ο κτηνοτρόφος",ch:"ΕΡΤ Βορείου Αιγαίου",l:"el",g:["smallrum"],kw:["ευλογι","επαγρύπνηση"]},
  {id:"egpb816jhRo",c:"health",t:"Θερμικό στρες στις αγελάδες",ch:"Lagopoulos Farm",l:"el",g:["cattle"],kw:["θερμικ","καύσων"]},
  {id:"BzlP87C1guU",c:"health",t:"Πρόβλεψη θερμικού στρες στις αγελάδες",ch:"AlphaNews Live",l:"el",g:["cattle"],kw:["θερμικ","καύσων"]},
  {id:"FTsXy6ifCio",c:"health",t:"Ασφάλεια & υγεία κοτόπουλων",ch:"Wikifarmer",l:"el",g:["poultry"],kw:["βιοασφάλ","κοτέτσ","γρίπη","άκαρ"]},
  // Άμελξη
  {id:"t92BY1i9kd8",c:"milk",t:"Πώς & πότε να αρμέξετε την κατσίκα",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["άμελξ","γάλα"]},
  {id:"cMfj_efYH00",c:"milk",t:"Αίθουσα αρμεγής προβάτων υψηλής γραμμής — διαστασιολόγηση",ch:"NIK UTB",l:"el",g:["smallrum"],kw:["άμελξ","αμελκτήρ"]},
  {id:"_D_xHgxdYjo",c:"milk",t:"Παγίδα αρμέγματος στο αμελκτήριο",ch:"NIK UTB",l:"el",g:["smallrum"],kw:["άμελξ","αμελκτήρ"]},
  // Γάλα & τυροκόμηση
  {id:"BmM7ZFB25dg",c:"dairy",t:"Σπιτική τυροκόμηση φέτας στο Κουτσελιό Ιωαννίνων",ch:"Olga Krana",l:"el",g:["smallrum","cattle"],kw:["γάλα","τυρ"]},
  {id:"p6T_j7vfCpQ",c:"dairy",t:"Το τυρί στη Λήμνο: τυροκόμηση στο τυροκομείο",ch:"MedINA",l:"el",g:["smallrum","cattle"],kw:["γάλα","τυρ"]},
  {id:"R6fC4zSCQcc",c:"dairy",t:"Φτιάχνω ξινοτύρι (ξινομυζήθρα)",ch:"KostasSpear",l:"el",g:["smallrum","cattle"],kw:["γάλα","τυρ"]},
  // Τοκετός & νεογέννητα
  {id:"HDFVvoRaIT4",c:"birth",t:"Γέννα κατσίκας",ch:"Manos Milolidakis",l:"el",g:["smallrum"],kw:["τοκετ","γέννα"]},
  {id:"2gch-7PpVF0",c:"birth",t:"Τα νεογέννητα κατσικάκια",ch:"Dimis Farmer Stories",l:"el",g:["smallrum"],kw:["νεογέν","τοκετ"]},
  {id:"keFkI_n5eOQ",c:"birth",t:"Η αξία του πρωτογάλακτος στα νεογέννητα αρνιά",ch:"Heliades Farming Solutions",l:"el",g:["smallrum"],kw:["πρωτόγαλ","νεογέν"]},
  {id:"lqQPiuNkRzg",c:"birth",t:"Γέννα μοσχαριού",ch:"LifeEvents",l:"el",g:["cattle"],kw:["τοκετ","γέννα"]},
  // Αναπαραγωγή
  {id:"iufR6N2U984",c:"repro",t:"Τεχνητή σπερματέγχυση",ch:"PROUD Farm Incubator",l:"el",g:["cattle","smallrum"],kw:["σπερματέγχ","οίστρ"]},
  {id:"JD8PkLontLs",c:"repro",t:"Προετοιμασία κριών για τις οχείες",ch:"Αγγελίνα Κυριακοπούλου",l:"el",g:["smallrum"],kw:["οχεία","κριαρ","τράγ","flushing"]},
  // Διατροφή & χορτονομή
  {id:"j6RFHapIQfM",c:"feed",t:"Πώς να ταΐσετε τα πρόβατα",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["σιτηρέσ","ζωοτροφ","διατροφ","βοσκ","συμπλήρωμα"]},
  {id:"Wt_WAEI-vlg",c:"feed",t:"Πώς να ταΐσετε τις κατσίκες",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["σιτηρέσ","ζωοτροφ","διατροφ","βοσκ"]},
  {id:"PsgaSsz69D0",c:"feed",t:"Διατροφή αγροτικών ζώων — βασικές αρχές, σιτηρέσιο",ch:"Innovation and Impact Hub",l:"el",g:["smallrum","cattle"],kw:["σιτηρέσ","ζωοτροφ","διατροφ"]},
  {id:"6c7i6-xKk_w",c:"feed",t:"Πρόβατα Ασσάφ: διατροφή & ποιότητα γάλακτος",ch:"Farma Hellas Genetics",l:"el",g:["smallrum"],kw:["σιτηρέσ","διατροφ","γάλα"]},
  {id:"1xHITRsKK3Y",c:"feed",t:"Σύγχρονη διατροφή & διαχείριση προβάτων Lacaune (σεμινάριο)",ch:"ΒΙΟΖΩΚΑΤ",l:"el",g:["smallrum"],kw:["σιτηρέσ","διατροφ","μετάβασ"]},
  {id:"aBD0gC27gU8",c:"feed",t:"Διατροφή & διαχείριση αιγοπροβάτων υψηλής γαλακτοπαραγωγής",ch:"ΒΙΟΖΩΚΑΤ (Zootechnia 2023)",l:"el",g:["smallrum"],kw:["σιτηρέσ","διατροφ","τοξαιμ"]},
  {id:"BKCIi37Me_E",c:"feed",t:"Κατάρτιση σιτηρεσίων αγελάδων γαλακτοπαραγωγής",ch:"Optimal Diet FS",l:"el",g:["cattle"],kw:["σιτηρέσ","διατροφ","μετάβασ","close-up"]},
  {id:"VPVKoDdbnEk",c:"feed",t:"Υγεία γαστρεντερικού των γαλακτοπαραγωγών αγελάδων (σεμινάριο)",ch:"ΒΙΟΖΩΚΑΤ",l:"el",g:["cattle"],kw:["οξέωση","σιτηρέσ","διατροφ"]},
  {id:"nj8Ei6o_5ag",c:"feed",t:"Ενσίρωση μηδικής (τριφύλλι)",ch:"Agro 83 GR",l:"el",g:["cattle","smallrum"],kw:["ενσίρωμα","ενσίρωση","τριφύλλ"]},
  {id:"Hgp8EQma8nU",c:"feed",t:"Ενσίρωση μηδικής — όλη η διαδικασία",ch:"Savvas Kefalas",l:"el",g:["cattle","smallrum"],kw:["ενσίρωμα","ενσίρωση","χορτονομ"]},
  // Χειρισμός, εγκαταστάσεις & περίφραξη
  {id:"UH5DxZZmTWI",c:"handle",t:"Υποστατικά αιγοπροβάτων",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["smallrum"],kw:["σταβλ","υποστατ","χειρισμ","αερισμ"]},
  {id:"JGPXByZ8FVc",c:"handle",t:"Σύγχρονη τεχνολογία στις μονάδες αγελαδοτροφίας",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["cattle"],kw:["σταβλ","άμελξ","τεχνολογ"]},
  {id:"f_HSfCqNGnk",c:"handle",t:"Ηλεκτρικός φράχτης για προστασία των οικόσιτων ζώων",ch:"Έξυπνο αγρόκτημα",l:"el",g:["all"],kw:["περίφραξ","θηρευτ"]},
  {id:"SA1tRri-5II",c:"handle",t:"Ελληνικά ποιμενικά κουτάβια: εκπαίδευση & μεγάλωμα",ch:"ΛΥΚΟΜΑΧΙΝ",l:"el",g:["dogs"],kw:["σκύλ","ποιμενικ"]},
  // Πουλερικά
  {id:"F9HJv6edpe8",c:"poultry",t:"Κοτέτσι εύκολο στην κατασκευή",ch:"Το Κανάλι του Γιάννη",l:"el",g:["poultry"],kw:["κοτέτσ","φωλι"]},
  {id:"6S4Vsa_f-MI",c:"poultry",t:"Θερμομάνα για νεοσσούς: τι πρέπει να προσέξω",ch:"KOTES.GR",l:"el",g:["poultry"],kw:["κλωσσομ","νεοσσ","θερμοκρασία θαλάμου"]},
  {id:"zTXGk4yqQX8",c:"poultry",t:"Χρήσιμες πληροφορίες για επιτυχημένη εκκόλαψη",ch:"Farma Jim Cott",l:"el",g:["poultry"],kw:["επώαση","εκκόλαψ"]},
  {id:"9SQTZN_JP8o",c:"poultry",t:"5 λάθη στην εκτροφή των ορτυκιών",ch:"Φάρμα «Η Ράχη»",l:"el",g:["poultry"],kw:["ορτύκ"]},
  {id:"rahXXnxJJs4",c:"poultry",t:"Πληροφορίες για τις πάπιες της φάρμας",ch:"Φάρμα «Η Ράχη»",l:"el",g:["poultry"],kw:["πάπι"]},
  {id:"KqOh4fRutDg",c:"poultry",t:"Πάπια Βαρβαρίας (Cairina moschata)",ch:"Φάρμα «Η Ράχη»",l:"el",g:["poultry"],kw:["πάπι"]},
  {id:"ISWNzLmbvW4",c:"poultry",t:"Γαλοπουλάκια τις πρώτες μέρες",ch:"Το Κανάλι του Γιάννη",l:"el",g:["poultry"],kw:["γαλοπ","νεοσσ"]},
  {id:"IlIYVtiXEUw",c:"poultry",t:"Το σωστό κλουβί για τους φασιανούς",ch:"Φάρμα πτηνών Peristeras P3",l:"el",g:["poultry"],kw:["φασιαν"]},
  {id:"FS6PcCI2lVQ",c:"poultry",t:"Φασιανοί & πέρδικες στο εκτροφείο θηραμάτων Νάουσας",ch:"vDimitris",l:"el",g:["poultry"],kw:["φασιαν","πέρδικ","θηραμ"]},
  {id:"AJ1g8B0pAE0",c:"poultry",t:"Εκτροφείο θηραμάτων Κυνηγετικού Συλλόγου Βόλου",ch:"Kynigesia",l:"el",g:["poultry"],kw:["πέρδικ","φασιαν","θηραμ"]},
  {id:"vjL0901tZqo",c:"poultry",t:"Νησιώτικες πέρδικες (Alectoris chukar)",ch:"Φάρμα «Η Ράχη»",l:"el",g:["poultry"],kw:["πέρδικ"]},
  {id:"4LiePtPGL9Y",c:"poultry",t:"Η πρώτη φάρμα στρουθοκαμήλων στην Ελλάδα",ch:"ΕΡΤ",l:"el",g:["poultry"],kw:["στρουθοκ"]},
  // Μελισσοκομία
  {id:"u6BaDdu2Apg",c:"bees",t:"Μελισσοκομία για αρχάριους, βήμα-βήμα",ch:"Ορεινή Μέλισσα",l:"el",g:["bees"],kw:["κυψέλ","μελίσσ"]},
  {id:"LXx2ekM2psk",c:"bees",t:"Πρακτικό σεμινάριο για αρχάριους μελισσοκόμους",ch:"EllinikoMeli",l:"el",g:["bees"],kw:["κυψέλ","μελίσσ"]},
  {id:"yV56TLaICxc",c:"bees",t:"Παραφυάδες χωρίς βασιλοτροφία & χωρίς μετακίνηση",ch:"Ορεινή Μέλισσα",l:"el",g:["bees"],kw:["παραφυάδ","σμηνουργ"]},
  {id:"uEJXqwfPrRw",c:"bees",t:"Μέθοδος Ντεμαρί για πρόληψη της σμηνουργίας",ch:"Δυτική Μέλισσα",l:"el",g:["bees"],kw:["σμηνουργ"]},
  {id:"Xf1Rl8ffR3A",c:"bees",t:"Τροφοδοσία μελισσών: πότε, πόσο, τι & γιατί",ch:"Στέργιος Στεργάτος",l:"el",g:["bees"],kw:["διέγερση","τροφ","σιρόπ","αποθεμ"]},
  {id:"VZ9xRKRDums",c:"bees",t:"Κανόνες εισαγωγής βασίλισσας για 100% αποδοχή",ch:"melistalaktos.gr",l:"el",g:["bees"],kw:["βασίλισσ","παραφυάδ"]},
  {id:"MOAOLZ2sEkM",c:"bees",t:"Οξαλικό οξύ με εξάχνωση κατά της βαρρόα",ch:"Ορεινό Μέλι",l:"el",g:["bees"],kw:["βαρρόα","οξαλικ"]},
  {id:"BgB5UShYPCY",c:"bees",t:"Έλεγχος βαρρόα μετά από οξαλικό & αμιτράζ",ch:"Rhodian bees",l:"el",g:["bees"],kw:["βαρρόα"]},
  {id:"z8n4Oq1k5M8",c:"bees",t:"Τρύγος ανθόμελου από παραφυάδες",ch:"Μελισσοκομία Melefsis",l:"el",g:["bees"],kw:["τρύγ","μέλι"]},
  {id:"bNO13uvRB_M",c:"bees",t:"Νέος μελισσοκόμος — οικογενειακή επιχείρηση",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["bees"],kw:["μελίσσ"]},
  // Εκτροφή ειδών
  {id:"eG_70lF72js",c:"species",t:"Πώς να μεγαλώσετε πρόβατα",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["πρόβατ"]},
  {id:"oweQj3w5dZw",c:"species",t:"Πώς να μεγαλώσω κατσίκες",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["κατσίκ","αίγ"]},
  {id:"FzCUTy7PweM",c:"species",t:"Πώς να φροντίσετε τις κατσίκες",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["κατσίκ","αίγ"]},
  {id:"QUvfSqlDFww",c:"species",t:"Πώς να επιλέξετε κατσίκια για γάλα & για κρέας",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["κατσίκ","φυλ"]},
  {id:"eAlmu2AJsfQ",c:"species",t:"Αιγοπροβατοτρόφος — οικογενειακή επιχείρηση",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["smallrum"],kw:["πρόβατ"]},
  {id:"AwqxQfYrBVs",c:"species",t:"Αγελαδοτρόφος — οικογενειακή επιχείρηση",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["cattle"],kw:["αγελάδ"]},
  {id:"QiNNqeDD_0Y",c:"species",t:"Η αγελαδοτροφία στην Ελλάδα",ch:"Dimis Farmer Stories",l:"el",g:["cattle"],kw:["αγελάδ"]},
  {id:"3cBtGSXI9KQ",c:"species",t:"Φάρμα Γκαντζώρα — εκτροφή βοοειδών",ch:"Dimis Farmer Stories",l:"el",g:["cattle"],kw:["μοσχάρ","βοοειδ","πάχυνση"]},
  {id:"MgOpDvn86Bc",c:"species",t:"Σε τι υπερέχει το καραγκούνικο πρόβατο",ch:"ΕΡΤ",l:"el",g:["smallrum"],kw:["καραγκούν","φυλ"]},
  {id:"t3CIVy41k0g",c:"species",t:"Η σπάνια φυλή προβάτων Φλώρινας-Πελαγονίας",ch:"ΕΡΤ",l:"el",g:["smallrum"],kw:["φλώριν","φυλ"]},
  {id:"hQwNb39RWM8",c:"species",t:"Το χιώτικο πρόβατο (Διευθυντής Κτηνιατρείου Χίου)",ch:"Alithia MME",l:"el",g:["smallrum"],kw:["χιώτικ","φυλ"]},
  {id:"qxaY4L6b4aM",c:"species",t:"Γίδια Σκοπέλου — μια σπάνια φυλή αιγών",ch:"Dimis Farmer Stories",l:"el",g:["smallrum"],kw:["σκοπέλ","φυλ"]},
  {id:"6Wy_SQBMfwQ",c:"species",t:"Αυτόχθονες φυλές αιγοπροβάτων (Gen Sheep Milk)",ch:"Innovation and Impact Hub",l:"el",g:["smallrum"],kw:["φυλ","αυτόχθον"]},
  {id:"DrRK7XRx0Pw",c:"species",t:"Τα βουβάλια της Κερκίνης χρειάζονται νερό & δροσιά",ch:"alterthess",l:"el",g:["cattle"],kw:["βουβάλ","θερμικ"]},
  {id:"vlxa-plk2rY",c:"species",t:"Φάρμα βουβαλιών — λίμνη Κερκίνη",ch:"Agro 83 GR",l:"el",g:["cattle"],kw:["βουβάλ"]},
  {id:"P4PMux2oSAM",c:"species",t:"Μαύρος χοίρος — από το χωράφι στο ράφι",ch:"ΕΡΤ",l:"el",g:["pig"],kw:["χοιρ"]},
  {id:"WZchKE12Xzc",c:"species",t:"Μαύρος χοίρος — συνεργασία ΕΚΕΤΑ με φάρμα",ch:"Fotiadis Farm",l:"el",g:["pig"],kw:["χοιρ"]},
  {id:"hvOexnyoV54",c:"species",t:"Ελάφια πλατώνια (ντάμα-ντάμα) — Κοζάνη",ch:"Ελληνικό Κέντρο Παρατήρησης",l:"el",g:["game"],kw:["ελάφ"]},
  {id:"RfRJ9ItZlhs",c:"species",t:"Η μοναδική φάρμα με ελάφια στην Κύπρο",ch:"AlphaNews Live",l:"el",g:["game"],kw:["ελάφ"]},
  {id:"3jTwLNWLn9Y",c:"species",t:"Μονάδα παραγωγής αγριογούρουνων",ch:"TV100 Θεσσαλονίκη",l:"el",g:["game"],kw:["αγριόχ","αγριογούρ"]},
  {id:"4HkvxHmBY6E",c:"species",t:"Η τέχνη του πεταλωτή",ch:"ΕΡΤ",l:"el",g:["equine"],kw:["πεταλ","οπλ"]},
  {id:"5_a1fM6_guM",c:"species",t:"Πετάλωμα αλόγων με τον Δημήτρη Μανάβη",ch:"Εμπρός Επικοινωνία Αιγαίου",l:"el",g:["equine"],kw:["πεταλ","οπλ"]},
  {id:"pF43cF9z_IE",c:"species",t:"Φάρμα με γαϊδουράκια στην Οινόη Κοζάνης",ch:"ΕΡΤ",l:"el",g:["equine"],kw:["γαϊδ"]},
  {id:"EXQHJeoKbUI",c:"species",t:"Τι να δίνουμε στα κουνέλια",ch:"Andreas Papastefanakis",l:"el",g:["rabbit"],kw:["κουνέλ","τροφ"]},
  {id:"lPyGesqTVLk",c:"species",t:"Η αναπαραγωγή των κουνελιών",ch:"FARMA A7",l:"el",g:["rabbit"],kw:["κουνέλ","αναπαραγ"]},
  {id:"z6hdohKkkNI",c:"species",t:"Η πρώτη μονάδα εκτροφής πέστροφας στην ορεινή Ροδόπη",ch:"ERT3",l:"el",g:["fish"],kw:["πέστροφ"]},
  {id:"c9bD4LL1Q88",c:"species",t:"Σουφλί: εκτροφή μεταξοσκώληκα",ch:"OPEN",l:"el",g:["insects"],kw:["μεταξοσκ"]}
);

/* ================= ΒΙΝΤΕΟ ΕΡΓΑΛΕΙΩΝ (v1.6) — χρήση, ρύθμιση & συντήρηση =================
   Νέα βίντεο (κατηγορία «🧰 Εργαλεία») + window.TOOL_VIDS: όνομα εργαλείου → IDs (εμφανίζονται πρώτα στο εργαλείο). */
window.VIDEO_CATS.tools="🧰 Εργαλεία: χρήση & συντήρηση";
[
  ["VqzgqeOsqlA","Στήσιμο κεφαλής κουρευτικής με χτένα & μαχαίρι","Freshly Peeled Sheep Shearing","en"],
  ["rcJZUtjp_tw","Τρόχισμα χτένας & μαχαιριού κουρευτικής","Heiniger Australia & NZ","en"],
  ["upItF9eMJR4","Συντήρηση κεφαλών κουρευτικής μηχανής","ΤΕΛΗΣ Γιάννενα","el"],
  ["yM5BptihUiM","Κούρεμα με ψαλίδι χειρός (βήμα-βήμα)","Allan the Shearer","en"],
  ["xwbBMMwxlFg","Ακόνισμα ψαλιδιού κουρέματος χειρός","Allan the Shearer","en"],
  ["ven7M8eQClI","Συντήρηση παλιών ψαλιδιών κουρέματος","ΤΕΛΗΣ Γιάννενα","el"],
  ["HUvzC4c5LUE","Κόψιμο οπλών αίγας/προβάτου: βήματα & εργαλεία","Goat Getter","en"],
  ["tBpgVQw09vc","Συμβουλές ακονίσματος μαχαιριού οπλών","American Farriers Journal","en"],
  ["ye0AiFN341c","Ακόνισμα μαχαιριού οπλών αγελάδας","Dairy Australia","en"],
  ["9TZxiXi_-nk","Ποδόλουτρο προβάτων κατά της χωλότητας","AHDB Beef & Lamb","en"],
  ["2y8jQO50BnI","Εφαρμογή σκευάσματος ποδόλουτρου (Hoofoss)","Vitfarm","el"],
  ["GFfxxaKTI8o","Βούρτσες & ξυστριά αλόγου: πώς χρησιμοποιούνται","Country and Stable","en"],
  ["TOByc_uDcAg","Πώς χρησιμοποιούμε το ξυστρί","Chastain Horse Park","en"],
  ["WUgWmOdxbrs","Κούρεμα βοοειδών με κουρευτική μηχανή","Irish Farmers Journal","en"],
  ["0dsZr_R8L8M","Κούρεμα βοοειδών πριν τον χειμερινό σταβλισμό","Teagasc","en"],
  ["ZH_9NWubids","Τοποθέτηση ενωτίων σε πρόβατα — οδηγός αρχαρίων","Dave and Jane","en"],
  ["Qrg2qf2txjg","Φόρτωση ηλεκτρονικών ενωτίων στον ενωτιοθέτη","Allflex North America","en"],
  ["5RkeMAfBb5s","Τοποθέτηση ενωτίων με τον ενωτιοθέτη Allflex","Tirlán FarmLife","en"],
  ["8YmCjGR_Ti4","Ηλεκτρονικά ενώτια προβάτων (eID)","Allflex Australia","en"],
  ["GRMf09HuFPE","Σύστημα ηλεκτρονικής σήμανσης (EID) στη μονάδα βοοειδών","U.S. CattleTrace","en"],
  ["Yft1Uj6hqEk","Πώς χρησιμοποιούμε τον αναγνώστη EID σε πρόβατα","BorderSoftware","en"],
  ["LiGuqPrptD4","Αναγνώστης ηλεκτρονικής σήμανσης (stick reader)","Shearwell Data","en"],
  ["9M4HyadL2Bo","Καταγραφή δεδομένων ζώων με αναγνώστη EID","Datamars Livestock","en"],
  ["VaMcApBajIY","Σημαδευτικό σπρέι ζώων — χρήση","Premier 1 Supplies","en"],
  ["0WeyuqtriFQ","Πώς φοράμε σαμάρι σημαδέματος στο κριάρι","SmallholderSeries (Adam Henson)","en"],
  ["gsDMipU5wmA","Ψυχρή σήμανση βοοειδών — πώς γίνεται","Angus TV","en"],
  ["B3vcV6wb9XE","Ψυχρή σήμανση με ξηρό πάγο","Sand Creek Ranch","en"],
  ["n4ECOJ32CVs","Υποδόριες & ενδομυϊκές ενέσεις σε ζώα","Reproduction Specialty Group","en"],
  ["cxZpQktw3Z8","Πώς χρησιμοποιούμε την αυτόματη σύριγγα","Farmers Partner","en"],
  ["piaL_VCYtIE","Αυτόματη σύριγγα Allflex με κτηνίατρο","Farmers Business Network","en"],
  ["0scTzo8ryFQ","Βαθμονόμηση πιστολιού χορήγησης (dosing gun)","Teagasc","en"],
  ["Kgc_WK-Iq88","Βαθμονόμηση πιστολιού ανθελμινθικού","Smart Sheep","en"],
  ["tmeZkqGQnMg","Εκπαίδευση στην τεχνική FAMACHA","University of Rhode Island","en"],
  ["vFNOWMIRlQE","Μέτρηση ορθικής θερμοκρασίας αγελάδας","NBC Field Service","en"],
  ["FqGuPJJkV-k","Πώς μετράμε τη θερμοκρασία του προβάτου","Gale Woods Farm","en"],
  ["dEyouroHsyA","Εξέταση κοιλίας μηρυκαστικών (ακρόαση)","University of Nottingham","en"],
  ["J3ZImuYRgMo","Φυσιολογικοί & παθολογικοί ήχοι πνευμόνων μηρυκαστικών","Egyptian veterinary doctor","en"],
  ["xuNa5ZJGUQk","Πώς περνάμε σωλήνα στη μεγάλη κοιλία","UT Extension","en"],
  ["3Q_b98iTNac","Οισοφαγικός καθετήρας για χορήγηση υγρών σε αγελάδα","NBC Field Service","en"],
  ["OUDVzX4OJNE","Χορήγηση με σωλήνα σε μοσχάρι","That's Farming","en"],
  ["YxKY-irNuPY","Ανακούφιση τυμπανισμού με τροκάρ","Bovine Doctor","en"],
  ["72-vEonMfFs","Τεστ CMT — επίδειξη","Interactive Content","en"],
  ["HVW62c9C-vU","Πώς κάνουμε μέτρηση McMaster","Martin K. Nielsen","en"],
  ["of9tpZg4zt8","Μέθοδος McMaster & επίπλευσης","UCD Veterinary Parasitology","en"],
  ["KmryfUl9Dhk","Συντήρηση αμελκτικής — πότε αλλάζουμε τα λάστιχα","Teagasc","en"],
  ["vj64c4m5oL0","Πώς λειτουργεί η αμελκτική μηχανή","ENKA TARIM","en"],
  ["ZAndmXDeL8w","Αρμεκτική μηχανή για 2 αγελάδες","KOTES.GR","el"],
  ["4QTxMBmnN3I","Αλλαγή λάστιχου θηλής & γιατί έχει σημασία","Dr. Muzzammil Hassan","en"],
  ["DvKhWdVxFXU","Αμελκτήριο αιγοπροβάτων γρήγορης εξόδου","SYLCOHELLAS","en"],
  ["21dBLQ2qHJs","Περιστροφικό αμελκτήριο προβάτων","Waikato Milking Systems","en"],
  ["V6CnmArHNc8","Κύκλος πλυσίματος ψυκτικής δεξαμενής γάλακτος","Eurotec (Packo)","en"],
  ["Ck6QM2_xNSw","Καθαρισμός δεξαμενής γάλακτος","Leaning Oaks Farm","en"],
  ["MbaXapcid5A","Κύπελλο απολύμανσης θηλών μετά την άμελξη","Welcome Home Farm","en"],
  ["FhEEY0pOGMg","Η σημασία της απολύμανσης θηλών πριν την άμελξη","Tom Wall","en"],
  ["9U-61lkBqKI","Πώς χρησιμοποιούμε φίλτρο γάλακτος","FairHillsFarm","en"],
  ["SEYUSNhuguQ","Τοποθέτηση μαιευτικών αλυσίδων στο μοσχάρι","Hilary Bruegl","en"],
  ["ML4f-20m5eo","Χρήση έλκυθρου εμβρύου (calf jack)","NBC Field Service","en"],
  ["Ht9smZbX8AA","Υποβοηθούμενος τοκετός με έλκυθρο εμβρύου","Gurteen College","en"],
  ["RHkT9kz2O8E","Λάμπα θέρμανσης ή θερμαντική πλάκα για νεοσσούς;","Ploughman's Backyard","en"],
  ["F2XFBwSOB5g","Πώς ταΐζουμε αρνί με μπιμπερό (σωστά)","Living With Pickles","en"],
  ["SnmDmKzO_1Y","Πώς κόβουμε τη θηλή μπιμπερό αρνιού","Premier 1 Supplies","en"],
  ["wZFqBjbnUGA","Αυτόματη θηλάστρα μοσχαριών","Daviesway (Holm & Laue)","en"],
  ["d03vYurXaX8","Στήσιμο θηλάστρας αρνιών","McCabe Feeds","en"],
  ["0y2WHxCNzYQ","Εκπαίδευση αρνιών να θηλάζουν από θηλάστρα","Lamlac","en"],
  ["Rdt766azjew","Έλεγχος ποιότητας πρωτογάλακτος","AHDB Dairy","en"],
  ["LBEvn5yICqQ","Διαθλασίμετρο Brix για το πρωτόγαλα","Cargill Animal Nutrition","en"],
  ["8f0jHeNlPGk","Απολύμανση ομφαλού μοσχαριού","CCE NWNY Dairy Team","en"],
  ["GJ2_7Hv3vsw","Ομφαλίτιδα στα μοσχάρια — πρόληψη","Farmers Weekly","en"],
  ["dwF9J2T1TqA","Απόψυξη σπέρματος & φόρτωση πιστολιού σπερματέγχυσης","John Cavalieri","en"],
  ["sL5KlYCMXwc","Σωστή απόψυξη αχύρου σπέρματος","Dairy School","en"],
  ["muAQEB7Fcvo","Φροντίδα & συντήρηση δοχείου υγρού αζώτου","MizzouRepro","en"],
  ["nafRHRcnf7U","Σωστός χειρισμός σπέρματος","Reproduction Specialty Group","en"],
  ["ZxHDQbZBthY","Φορητός υπέρηχος για γονιμότητα & κυοφορία αγελάδων","Vet Solutions","en"],
  ["j8ZHjzzuZNg","Πώς τοποθετούμε CIDR σε αγελάδα","UK Martin-Gatton CAFE","en"],
  ["4bfQ_AUWubA","Τοποθέτηση σπόγγων σε προβατίνες","JP Smith","en"],
  ["sZ9q86SFvjc","Αφαίρεση σπόγγων & συγχρονισμός","JP Smith","en"],
  ["ATOS5X-5L9g","Πώς χρησιμοποιούμε την πένσα ελαστικών δακτυλίων","Farmers Business Network","en"],
  ["37Y6Q0dYTew","Η μέθοδος Burdizzo στις αίγες","The Farmhouse Mom","en"],
  ["oUuybRbitRg","Λάθη & λύσεις με τη λαβίδα Burdizzo","For the Love of Goats","en"],
  ["5hW_fHblx5A","Ταΐστρες προβάτων: εναλλακτικά σχέδια","Scotland's Farm Advisory Service","en"],
  ["gJNBs-uCElU","Ταΐστρες αιγοπροβάτων","Rolling O Farm","en"],
  ["g5fpLEfTLWg","Τοποθέτηση φλοτέρ για αυτόματη ποτίστρα","thewindmillgarden","en"],
  ["02G-scDDZQk","Σωστή φόρτωση κάθετου αναμικτήρα TMR","Jaylor","en"],
  ["zC98BlsUgzE","Σταθερό & ομοιόμορφο ανακάτεμα TMR","CCE NWNY Dairy Team","en"],
  ["d2O3aRt6sJc","Πώς βελτιστοποιούμε τον αναμικτήρα","Trioliet","en"],
  ["GvnQrpA1PXM","Σπαστήρας/μύλος καρπών σε λειτουργία","Degelman Industries","en"],
  ["M62My0t5DIU","Μπορούν τα πρόβατα να πάρουν χαλκό;","The Recreational Homestead","en"],
  ["FvJdAiKCtDM","Τα μεταλλικά στοιχεία που χρειάζονται τα πρόβατα","Tanner Farmstead","en"],
  ["7RMoVqVH4EA","Πώς καθαρίζουμε τον στάβλο του αλόγου","My New Horse","en"],
  ["IXUKFzMGDAc","Καθαρισμός στάβλου για υγιή ζώα","Lazy River Farms","en"],
  ["uT0GAkWog44","Πώς πιάνουμε πρόβατο με τη γκλίτσα","Ambry Acres","en"],
  ["7qETmkJxl_0","Γκλίτσα ποδιού — χρήση","TheSh3pherdess","en"],
  ["mohXeTZnyRU","Ζυγαριές για πρόβατα & αίγες","Grandview Livestock","en"],
  ["J641K4yDWV8","Πώς χρησιμοποιούμε τη μετροταινία βάρους","Wintape","en"],
  ["nSk2ZtlEeKI","Ασφαλής χειρισμός βοοειδών","Teagasc","en"],
  ["Gvom6eYsEo8","Εύκολη συντήρηση κλωβού ακινητοποίησης","Farm Learning with Tim Thompson","en"],
  ["N-RebaVLV8s","Μαντρί με πόρτα διαλογής 3 κατευθύνσεων","O'Donovan Engineering","en"],
  ["mDhee0qub9U","Πώς δένουμε την αγελάδα με καπίστρι","Mastermind Pro","en"],
  ["gOUiXMZpaEY","Πώς φτιάχνουμε καπίστρι από σχοινί","SootrakKnots","en"],
  ["GOP7eN5SrRc","Καπίστρι — τεχνική μεγάλων ζώων","OSU Large Animal Techniques","en"],
  ["PsoTEhrJQbU","Ασφάλεια τρακτέρ: πρόληψη ανατροπής","Ally Safety","en"],
  ["_us8i544-ek","Πλαίσιο προστασίας από ανατροπή (ROPS)","Mississippi State Extension","en"],
  ["0qSy6HgRR_c","Χορτοκοπτικό-διαμορφωτής σε τριφύλλι","Vermeer Agriculture","en"],
  ["p1XmWw8-qHw","Ήπια διαμόρφωση μηδικής με ρολά","KRONE","en"],
  ["j7KiaWyf8Y0","Γυρναρίστρα-χορτοσυλλέκτης: πώς λειτουργεί","Agri-Linc","en"],
  ["Oyxzp9g4oa0","Χορτοσυλλέκτες: ρότορας ή τροχοί;","Machinery Nation","en"],
  ["-x4Z4S1ojYs","Δεματοποίηση πρώτου χεριού τριφυλλιού","Farm Life SD","en"],
  ["ZzMwdxX6dhY","Δέσιμο τριφυλλιού στο Γόνιμο","makisgonimo","el"],
  ["k7rq9hIKw08","Ενσιρωτής για ποιοτικό ενσίρωμα","CLAAS UK","en"],
  ["qBWXxJGhtUM","Περιτυλικτικό κυλινδρικών δεμάτων","Tanco","en"],
  ["i6mWOA0u9hI","Ενσίρωμα σε ένα πέρασμα: σειράδιασμα, δεματοποίηση, τύλιγμα","Tractorspotter","en"],
  ["CWUL_do_6UA","Τηλεσκοπικός φορτωτής σε γαλακτοπαραγωγή μονάδα","10th Generation Dairyman","en"],
  ["XzJ8jXMx-oA","Τα βασικά της γείωσης ηλεκτροφόρου περίφραξης","RayWhiteKeatley","en"],
  ["1b4gJBuGXL0","Έλεγχος ενεργοποιητή ηλεκτρικής περίφραξης","Fencer Fixer Repair","en"],
  ["22DCsZDJj-Y","Ηλεκτροφόρο δίχτυ περίφραξης για αίγες — στήσιμο","Bri From Scratch","en"],
  ["kfpNgP7VRpc","Κολάρα εικονικής περίφραξης GPS για βοοειδή","Riverview Ranch","en"],
  ["fc04XM8cn-0","Κλωσσομηχανές: οδηγίες χρήσης & λειτουργίας","Biostalis","el"],
  ["zHJaPqa3Eh0","Πώς λειτουργεί η εκκολαπτική μηχανή","Κτήμα Λαγκώνα","el"],
  ["K34hMjhT-yo","Ωοσκόπηση από την 1η ως την 21η ημέρα","Animals Life","en"],
  ["7eniFKIfExk","Πώς συνηθίζουν οι κότες τις ποτίστρες θηλής","Raising Happy Chickens","en"],
  ["vG0NqRduEGU","Αυτόματη ποτίστρα θηλής για κότες (κατασκευή)","Field to Farm","en"],
  ["XTCBbkKwO1s","Συμβουλές για φωλιές ωοτοκίας","Joel Salatin","en"],
  ["L2TuMGMOnOQ","Πώς φτιάχνουμε φωλιές για κότες","Bock Bock Bouquet","en"],
  ["6dnQetJPqfU","Πώς σταματάμε το κόκκινο άκαρι στο κοτέτσι","The Smallholding Diaries","en"],
  ["55rgOuRjbsA","Καπνιστήρι: πώς το ανάβω","8520mp","el"],
  ["VCoJCrFQ-RY","Καύσιμα για το καπνιστήρι","8520mp","el"],
  ["a3CTSXxRmug","Πώς ανάβουμε το καπνιστήρι ώστε να μένει αναμμένο","Black Mountain Honey","en"],
  ["ECXRxi2Gg9s","Πώς χρησιμοποιούμε το ξέστρο κυψέλης","UF Honey Bee Lab","en"],
  ["mfhDV0hggCg","Το ξέστρο κυψέλης — βασικά","Elzner Farms","en"],
  ["rjmXCte90fs","Επιλογή στολής, μπουφάν ή μάσκας μελισσοκόμου","Betterbee","en"],
  ["ZyHGdq0CRUc","Η κυψέλη Langstroth και τα μέρη της","UF Honey Bee Lab","en"],
  ["lKIO53g6WcI","Βασιλικό διάφραγμα: πώς & πότε","The Bee Supply","en"],
  ["vKcn1vM1HPI","Μελιτοεξαγωγέας 10 πλαισίων","EllinikoMeli","el"],
  ["cFKGU2gcPwA","Μελιτοεξαγωγέας — παρουσίαση","Melissocosmos","el"],
  ["usuSbFkqvoc","Πώς χρησιμοποιούμε τον μελιτοεξαγωγέα (6 βήματα)","Bee Professor","en"],
  ["A7Cuhzx4yZc","Εργαλεία ξεκαπακώματος: ποιο δουλεύει καλύτερα","Kuenzer Homesteading","en"],
  ["y3u748aAy14","Τροφοδότης πλαισίου","ANEL","el"],
  ["UrN5Ydt1-xA","Τροφοδότης οροφής με σήτα επίπλευσης","ANEL","el"],
  ["RoiiL2u1VbU","Σύγκριση τροφοδοτών κυψέλης","Betterbee","en"],
  ["VK3zNIMSpps","Εξαχνωτής οξαλικού με ασφάλεια: δόση, προστασία, τεχνική","Lorob Bees","en"],
  ["x6VtgOZD-1o","Μέτρηση διαλυμένου οξυγόνου στην υδατοκαλλιέργεια","HORIBA","en"],
  ["FGRuvX4AlhU","Παρακολούθηση οξυγόνου κατά το τάισμα ψαριών","BP Milling","en"],
  ["BW5zvBxr6RM","Οι ανάγκες οξυγόνου της ιχθυοκαλλιέργειας","BP Milling","en"],
  ["WHSPD8Df3h0","Τοποθέτηση ανεμιστήρων στους στάβλους","Warren County Agriculture","en"],
  ["TVAZGgqvIfM","Ψύξη αγελάδων με γραμμές διαβροχής","VES-Artex","en"]
].forEach(([id,t,ch,l])=>{ if(!window.VIDEOS.some(v=>v.id===id)) window.VIDEOS.push({id,c:"tools",t,ch,l,g:["all"],kw:[]}); });
window.TOOL_VIDS = {
  "Ηλεκτρική κουρευτική μηχανή":["upItF9eMJR4","vIOJJIAyRnY","VqzgqeOsqlA","rcJZUtjp_tw"],
  "Ψαλίδι κουρέματος χειρός":["ven7M8eQClI","yM5BptihUiM","xwbBMMwxlFg"],
  "Ψαλίδι οπλών":["dS2UWpAp7cA","HUvzC4c5LUE","3TqV7JDOGPY"],
  "Μαχαίρι οπλών & ράσπα":["pUA_ehSw1yc","tBpgVQw09vc","ye0AiFN341c"],
  "Ποδόλουτρο":["2y8jQO50BnI","9TZxiXi_-nk","VklHIlJ81-A"],
  "Ξυστρί & βούρτσες":["GFfxxaKTI8o","TOByc_uDcAg"],
  "Κουρευτική μηχανή αλόγων/βοοειδών":["WUgWmOdxbrs","0dsZr_R8L8M"],
  "Ενώτια (ταμπελάκια αυτιού)":["ZH_9NWubids","xQq1BhGelDc","PDadfJMnj24"],
  "Ενωτιοθέτης (πένσα ενωτίων)":["5RkeMAfBb5s","Qrg2qf2txjg"],
  "Ηλεκτρονικό ενώτιο / βώλος RFID":["8YmCjGR_Ti4","GRMf09HuFPE"],
  "Αναγνώστης RFID ζώων (stick reader)":["Yft1Uj6hqEk","LiGuqPrptD4","9M4HyadL2Bo"],
  "Σημαδευτικό σπρέι & κηρομπογιές":["VaMcApBajIY"],
  "Σαμάρι σημαδέματος κριού (raddle)":["u15UbhJtsKA","0WeyuqtriFQ"],
  "Ψυχρή σήμανση (freeze branding)":["gsDMipU5wmA","B3vcV6wb9XE"],
  "Σύριγγες & βελόνες":["94P_JEQDobg","n4ECOJ32CVs"],
  "Αυτόματη σύριγγα εμβολιασμού (πιστόλι)":["cxZpQktw3Z8","piaL_VCYtIE"],
  "Δοσομετρικό πιστόλι ανθελμινθικών (drench gun)":["0scTzo8ryFQ","Kgc_WK-Iq88","m0TFBU75DiM"],
  "Κάρτα FAMACHA©":["tmeZkqGQnMg","KYFUAvFQ15g"],
  "Κτηνιατρικό θερμόμετρο":["vFNOWMIRlQE","FqGuPJJkV-k"],
  "Στηθοσκόπιο":["dEyouroHsyA","J3ZImuYRgMo"],
  "Οισοφαγικός καθετήρας":["xuNa5ZJGUQk","3Q_b98iTNac","OUDVzX4OJNE","P7PUU1eLZIQ"],
  "Τροκάρ τυμπανισμού":["YxKY-irNuPY"],
  "Κιτ CMT (τεστ μαστίτιδας)":["ClL88f6FKB0","72-vEonMfFs","7WtMTV-rjlQ"],
  "Μικροσκόπιο & θάλαμος McMaster":["HVW62c9C-vU","of9tpZg4zt8","aGj4L75lp5U"],
  "Αμελκτική μηχανή":["ZAndmXDeL8w","KmryfUl9Dhk","vj64c4m5oL0"],
  "Σετ άμελξης (κάλυκες & συλλέκτης)":["4QTxMBmnN3I","KmryfUl9Dhk"],
  "Αμελκτήριο (μονάδα άμελξης)":["cMfj_efYH00","DvKhWdVxFXU","21dBLQ2qHJs"],
  "Ψυκτική δεξαμενή γάλακτος":["V6CnmArHNc8","Ck6QM2_xNSw"],
  "Κύπελλο απολύμανσης θηλών (teat dip)":["MbaXapcid5A","FhEEY0pOGMg","XWW-Pwe8Ac4"],
  "Φίλτρα & σουρωτήρι γάλακτος":["9U-61lkBqKI"],
  "Αλυσίδες/σχοινιά τοκετού & λαβές":["vJRDvhb8QUQ","SEYUSNhuguQ"],
  "Έλκυθρο εμβρύου (calf jack)":["ML4f-20m5eo","Ht9smZbX8AA"],
  "Λάμπα θέρμανσης (υπέρυθρη)":["RHkT9kz2O8E"],
  "Μπιμπερό & θηλές αρνιών/κατσικιών":["F2XFBwSOB5g","SnmDmKzO_1Y","XQfSWLBIegw"],
  "Αυτόματη θηλάστρα (γαλακτοδότης)":["d03vYurXaX8","0y2WHxCNzYQ","wZFqBjbnUGA"],
  "Διαθλασίμετρο Brix (πρωτόγαλα)":["Rdt766azjew","LBEvn5yICqQ"],
  "Ιώδιο για τον ομφαλό":["8f0jHeNlPGk","GJ2_7Hv3vsw"],
  "Πιστόλι σπερματέγχυσης":["dwF9J2T1TqA","sL5KlYCMXwc","h69GQPQXXBE"],
  "Δοχείο υγρού αζώτου (dewar)":["muAQEB7Fcvo","nafRHRcnf7U"],
  "Φορητός υπέρηχος":["ZxHDQbZBthY","VZFTmPlzuWo"],
  "Σπόγγοι/CIDR συγχρονισμού οίστρου":["uBctCa7nLnw","4bfQ_AUWubA","sZ9q86SFvjc","j8ZHjzzuZNg"],
  "Ελαστικοί δακτύλιοι & πένσα (elastrator)":["ATOS5X-5L9g","t7LfOyU6BSA"],
  "Λαβίδα Burdizzo (αναίμακτος ευνουχισμός)":["37Y6Q0dYTew","oUuybRbitRg"],
  "Ταΐστρα / φάτνη":["5hW_fHblx5A","gJNBs-uCElU"],
  "Αυτόματη ποτίστρα":["g5fpLEfTLWg"],
  "Αναμικτήρας-διανομέας (TMR mixer)":["nphZ2P1yivs","02G-scDDZQk","zC98BlsUgzE","d2O3aRt6sJc"],
  "Σπαστήρας/μύλος καρπών":["GvnQrpA1PXM"],
  "Γλειφόμενο αλάτι / ιχνοστοιχεία":["M62My0t5DIU","FvJdAiKCtDM"],
  "Πηρούνα, φτυάρι & καρότσι":["7RMoVqVH4EA","IXUKFzMGDAc"],
  "Γκλίτσα (ποιμενική ράβδος)":["uT0GAkWog44","7qETmkJxl_0"],
  "Ζυγαριά ζώων":["mohXeTZnyRU"],
  "Μετροταινία βάρους":["J641K4yDWV8","BWGksusrdHs"],
  "Κλωβός ακινητοποίησης (cattle crush)":["nSk2ZtlEeKI","Gvom6eYsEo8"],
  "Διάδρομος & μαντρί διαλογής αιγοπροβάτων":["N-RebaVLV8s","J3ed7U5SRrA"],
  "Καπίστρι & σχοινί οδήγησης":["mDhee0qub9U","gOUiXMZpaEY","GOP7eN5SrRc"],
  "Τρακτέρ":["PsoTEhrJQbU","_us8i544-ek"],
  "Χορτοκοπτικό (δισκοφόρο)":["JkXm6RNtOsg","0qSy6HgRR_c","p1XmWw8-qHw"],
  "Χορτοσυλλέκτης / γυρναρίστρα":["j7KiaWyf8Y0","Oyxzp9g4oa0"],
  "Δεματοποιητική (πρέσα)":["ZzMwdxX6dhY","-x4Z4S1ojYs","JkXm6RNtOsg"],
  "Ενσιρωτής (κοπτικό ενσίρωσης)":["v4zHpdszJiI","k7rq9hIKw08"],
  "Περιτυλικτικό μπαλών (μπαλοενσίρωση)":["nj8Ei6o_5ag","qBWXxJGhtUM","i6mWOA0u9hI"],
  "Τηλεσκοπικός φορτωτής":["CWUL_do_6UA"],
  "Ηλεκτροφόρος περίφραξη (ενεργοποιητής)":["uTimrjgDa80","XzJ8jXMx-oA","1b4gJBuGXL0"],
  "Πλέγμα / συρματόπλεγμα περίφραξης":["22DCsZDJj-Y"],
  "Κολάρο GPS ζώων":["kfpNgP7VRpc"],
  "Εκκολαπτική μηχανή":["fc04XM8cn-0","zHJaPqa3Eh0","IRTf__2M7qg"],
  "Ωοσκόπιο":["LLdKVwSfcpc","K34hMjhT-yo"],
  "Κλωσσομητέρα (θερμαντικό)":["6S4Vsa_f-MI","RHkT9kz2O8E","NmvExuW2cM8"],
  "Ποτίστρα καμπάνα / θηλές (nipple)":["7eniFKIfExk","vG0NqRduEGU"],
  "Φωλιές ωοτοκίας":["XTCBbkKwO1s","L2TuMGMOnOQ"],
  "Κουρνιαχτές (κούρνιες)":["6dnQetJPqfU"],
  "Καπνιστήρι":["55rgOuRjbsA","VCoJCrFQ-RY","a3CTSXxRmug"],
  "Ξέστρο κυψέλης (hive tool)":["ECXRxi2Gg9s","mfhDV0hggCg"],
  "Στολή & μάσκα μελισσοκόμου":["rjmXCte90fs"],
  "Κυψέλη Langstroth & πλαίσια":["ZyHGdq0CRUc"],
  "Βασιλικό διάφραγμα":["lKIO53g6WcI"],
  "Μελιτοεξαγωγέας":["vKcn1vM1HPI","cFKGU2gcPwA","usuSbFkqvoc"],
  "Πιρούνι/μαχαίρι ξεκαπακώματος":["1iqfW_0EHVw","A7Cuhzx4yZc"],
  "Τροφοδότης (σιρόπι/ζαχαροζύμαρο)":["y3u748aAy14","UrN5Ydt1-xA","Xf1Rl8ffR3A","RoiiL2u1VbU"],
  "Εξαχνωτής/ταινίες κατά βαρρόα":["MOAOLZ2sEkM","3iQmbGNRO1w","VK3zNIMSpps"],
  "Οξυγονόμετρο νερού":["x6VtgOZD-1o","FGRuvX4AlhU"],
  "Αεριστήρας / αντλία αέρα":["BW5zvBxr6RM"],
  "Ανεμιστήρες & υδρονέφωση":["WHSPD8Df3h0","TVAZGgqvIfM"]
};
