/* ================= ΚΤΗΝΟΤΡΟΦΟΣ ΤΝ — ΒΙΝΤΕΟ ΕΡΓΑΣΙΩΝ =================
   Φορτώνουν ΜΟΝΟ με κλικ, από youtube-nocookie.com (αυξημένη ιδιωτικότητα).
   id: YouTube ID (ελεγμένο με oEmbed) · t: ελληνική περιγραφή · ch: κανάλι · l: γλώσσα (el/en)
   g: ομάδες ζώων ή ["all"] · kw: λέξεις-κλειδιά εργασίας (σύνδεση με Πρόγραμμα ΤΝ & Εργαλεία) */
window.VIDEO_CATS = {care:"✂️ Περιποίηση & σήμανση",health:"💉 Υγεία & θεραπεία",milk:"🥛 Άμελξη",birth:"🍼 Τοκετός & νεογέννητα",repro:"🤰 Αναπαραγωγή",feed:"🌾 Διατροφή & χορτονομή",handle:"🚧 Χειρισμός & περίφραξη",poultry:"🐣 Πουλερικά",bees:"🐝 Μελισσοκομία",species:"🐾 Εκτροφή ειδών"};
window.VIDEOS = [
  // Περιποίηση & σήμανση
  {id:"uoI8F6gmdmg",c:"care",t:"Παραδοσιακός & μηχανικός τρόπος κουρέματος προβάτων",ch:"Thanasis Katopodis",l:"el",g:["smallrum"],kw:["κούρεμα"]},
  {id:"vIOJJIAyRnY",c:"care",t:"Κουρευτική μηχανή προβάτων: ρύθμιση & λίπανση",ch:"VlachosTools",l:"el",g:["smallrum"],kw:["κούρεμα"]},
  {id:"3TqV7JDOGPY",c:"care",t:"Περιποίηση οπλών αιγοπροβάτων για αρχάριους",ch:"NC State Extension",l:"en",g:["smallrum"],kw:["οπλ","νυχ","χωλότ","σήψη"]},
  {id:"pUA_ehSw1yc",c:"care",t:"Κοπή νυχιών αγελάδας — ολλανδική μέθοδος (5 βήματα)",ch:"Irish Farmers Journal",l:"en",g:["cattle"],kw:["οπλ","νυχ","χωλότ"]},
  {id:"VklHIlJ81-A",c:"care",t:"Αντιμετώπιση χωλότητας με ποδόλουτρο",ch:"Teagasc",l:"en",g:["smallrum","cattle"],kw:["ποδόλουτρ","σήψη","οπλ","χωλότ"]},
  {id:"xQq1BhGelDc",c:"care",t:"Τοποθέτηση ενωτίων σε πρόβατα",ch:"CanSheepFed",l:"en",g:["smallrum"],kw:["σήμανση","ενώτι"]},
  {id:"PDadfJMnj24",c:"care",t:"Τοποθέτηση ενωτίων σε μοσχάρια",ch:"Shearwell Data",l:"en",g:["cattle"],kw:["σήμανση","ενώτι"]},
  {id:"9jV74vgYv2w",c:"care",t:"Κούρεμα αλπακά από την αρχή ως το τέλος",ch:"Adam Riley",l:"en",g:["other"],kw:["κούρεμα"]},
  {id:"kDCdzWOzPKs",c:"care",t:"Περιποίηση μακριών οπλών αλόγου",ch:"Idaho Horseshoeing School",l:"en",g:["equine"],kw:["πεταλ","οπλ"]},
  // Υγεία & θεραπεία
  {id:"bpiPDjBzvMc",c:"health",t:"Εμβόλια προβάτων — εμπειρία κτηνοτρόφου",ch:"Η Φάρμα της Γιαγιάς",l:"el",g:["smallrum"],kw:["εμβολ","κλωστηρ"]},
  {id:"94P_JEQDobg",c:"health",t:"Υποδόρια ένεση σε αιγοπρόβατα (σωστή τεχνική)",ch:"Tri-State Veterinary Service",l:"en",g:["smallrum","other"],kw:["εμβολ","ένεση","κλωστηρ"]},
  {id:"TWKcDJ0on9Y",c:"health",t:"Χειρισμός & ενέσεις σε χοιρίδια (σίδηρος)",ch:"Michigan Pork Producers",l:"en",g:["pig"],kw:["σίδηρ","ένεση","χοιρίδ"]},
  {id:"m0TFBU75DiM",c:"health",t:"Σωστή τεχνική χορήγησης ανθελμινθικού (drench)",ch:"AHDB Beef & Lamb",l:"en",g:["smallrum","cattle","game","other"],kw:["αποπαρασ","ανθελμ"]},
  {id:"KYFUAvFQ15g",c:"health",t:"Παράσιτα αιγών: βαθμολόγηση FAMACHA",ch:"Oklahoma State Extension",l:"en",g:["smallrum","other","game"],kw:["famacha","αναιμ","αποπαρασ"]},
  {id:"aGj4L75lp5U",c:"health",t:"Κοπρανοσκόπηση — μέτρηση αυγών παρασίτων",ch:"N.C. Cooperative Extension",l:"en",g:["smallrum","cattle","equine","other","game"],kw:["κοπρανοσκόπ","αποπαρασ"]},
  {id:"xnDxJpIb5oo",c:"health",t:"Βαθμολόγηση σωματικής κατάστασης (BCS) προβάτων",ch:"UConn Extension",l:"en",g:["smallrum"],kw:["σωματικ","bcs","flushing","τοξαιμ"]},
  {id:"wASXNn_CTCU",c:"health",t:"Βαθμολόγηση σωματικής κατάστασης αγελάδων",ch:"Penn State Extension",l:"en",g:["cattle"],kw:["σωματικ","bcs","ξήρανση","μετάβασ"]},
  {id:"7WtMTV-rjlQ",c:"health",t:"Τεστ μαστίτιδας CMT σε αγελάδες",ch:"Penn State Extension",l:"en",g:["cattle","smallrum"],kw:["μαστίτ","cmt","ξήρανση"]},
  {id:"K0ngaaHYET4",c:"health",t:"Τυμπανισμός αρνιών — τι είναι στην πραγματικότητα (κτηνίατρος)",ch:"Sez the Vet",l:"en",g:["smallrum","cattle"],kw:["τυμπαν"]},
  // Άμελξη
  {id:"H729x8mPmpU",c:"milk",t:"Πρόβατα φυλής Χίου στο αμελκτήριο",ch:"Ioannis Giannopoulos",l:"el",g:["smallrum"],kw:["άμελξ","γάλα"]},
  {id:"MB9xhbNl-f4",c:"milk",t:"Αρμεγή & γαλακτομέτρηση προβάτων Ασσάφ",ch:"Farma Hellas Genetics",l:"el",g:["smallrum"],kw:["άμελξ","γάλα"]},
  {id:"MXmgzLfUtUI",c:"milk",t:"Περιστροφικό αμελκτήριο αγελάδων",ch:"Πανκτηνοτροφική",l:"el",g:["cattle"],kw:["άμελξ","γάλα"]},
  {id:"XWW-Pwe8Ac4",c:"milk",t:"Καλή πρακτική άμελξης — εμβάπτιση θηλών",ch:"Interactive Content",l:"en",g:["cattle","smallrum"],kw:["άμελξ","μαστίτ"]},
  // Τοκετός & νεογέννητα
  {id:"XsAcoGzUt5Q",c:"birth",t:"Προετοιμασία των μοσχίδων για τον τοκετό",ch:"EURCAW Ruminants & Equines",l:"el",g:["cattle"],kw:["τοκετ","μετάβασ","close-up","ξήρανση"]},
  {id:"Yh6o2Fu4SqE",c:"birth",t:"Πότε & πώς επεμβαίνουμε σε δύσκολο τοκετό αγελάδας",ch:"Beef Cattle Research Council",l:"en",g:["cattle"],kw:["τοκετ","δυστοκ"]},
  {id:"vJRDvhb8QUQ",c:"birth",t:"Σωστή τοποθέτηση αλυσίδων τοκετού",ch:"Progressive Dairy",l:"en",g:["cattle"],kw:["τοκετ","δυστοκ"]},
  {id:"Sbnwn3ODrkU",c:"birth",t:"Βοήθεια σε τοκετό προβατίνας — τα βασικά",ch:"Shropshire Farm Vets",l:"en",g:["smallrum"],kw:["τοκετ","δυστοκ","γέννα"]},
  {id:"VI4aTgt8q2s",c:"birth",t:"Ορθές πρακτικές χορήγησης πρωτογάλακτος στα νεογέννητα αρνιά",ch:"Innovation and Impact Hub",l:"el",g:["smallrum"],kw:["πρωτόγαλ","νεογέν","τοκετ"]},
  {id:"XQfSWLBIegw",c:"birth",t:"Τεχνητός θηλασμός & επιτυχημένη ανάπτυξη αρνιών",ch:"Innovation and Impact Hub",l:"el",g:["smallrum"],kw:["θηλασ","απογαλ","τεχνητ"]},
  {id:"P7PUU1eLZIQ",c:"birth",t:"Τάισμα αρνιών/κατσικιών με οισοφαγικό σωλήνα",ch:"Purdue Extension",l:"en",g:["smallrum"],kw:["πρωτόγαλ","οισοφαγ","νεογέν"]},
  {id:"t7LfOyU6BSA",c:"birth",t:"Κοπή ουράς αρνιών με ελαστικό δακτύλιο (καλή πρακτική)",ch:"Animal Health Australia",l:"en",g:["smallrum"],kw:["ευνουχ","ουρ","δακτύλ"]},
  // Αναπαραγωγή
  {id:"gVdqsXCYKBM",c:"repro",t:"Διαχείριση αιγοπροβάτων την εποχή του ζευγαρώματος",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["smallrum"],kw:["οχεία","flushing","κριαρ","τράγ"]},
  {id:"uBctCa7nLnw",c:"repro",t:"Συγχρονισμός προβάτων για σπερματέγχυση",ch:"MANTIS Farm management",l:"el",g:["smallrum"],kw:["συγχρον","σπόγγ","οχεία","οίστρ"]},
  {id:"h69GQPQXXBE",c:"repro",t:"Τεχνητή σπερματέγχυση προβάτου",ch:"MANTIS Farm management",l:"el",g:["smallrum"],kw:["σπερματέγχ"]},
  {id:"stvnGYcKz60",c:"repro",t:"Τεχνητή σπερματέγχυση βοοειδών",ch:"SUNUP TV (Oklahoma State)",l:"en",g:["cattle"],kw:["σπερματέγχ","οίστρ"]},
  {id:"VZFTmPlzuWo",c:"repro",t:"Υπερηχογράφημα κυοφορίας προβάτων",ch:"Texas A&M Sheep and Goats",l:"en",g:["smallrum"],kw:["κυοφορ","διάγνωση","υπέρηχ"]},
  {id:"u15UbhJtsKA",c:"repro",t:"Πώς φοράμε το σαμάρι σημαδέματος στο κριάρι",ch:"NETTEX",l:"en",g:["smallrum"],kw:["οχεία","κριαρ","σημάδ"]},
  // Διατροφή & χορτονομή
  {id:"nphZ2P1yivs",c:"feed",t:"Ολικό σιτηρέσιο (TMR) σε πρόβατα Ασσάφ",ch:"Pimenas",l:"el",g:["smallrum"],kw:["σιτηρέσ","tmr","ζωοτροφ","διατροφ"]},
  {id:"WNYU34eUu24",c:"feed",t:"Αναμικτήρες TMR: σύγκριση τύπων",ch:"KUHN",l:"en",g:["cattle","smallrum"],kw:["σιτηρέσ","tmr","ζωοτροφ"]},
  {id:"v4zHpdszJiI",c:"feed",t:"Ενσίρωση καλαμποκιού σε σάκο",ch:"MANTIS Farm management",l:"el",g:["cattle","smallrum"],kw:["ενσίρωμα","ενσίρωση"]},
  {id:"JkXm6RNtOsg",c:"feed",t:"Συγκομιδή τριφυλλιού: κόψιμο, γύρισμα, δέσιμο",ch:"Xristos Katsoulas",l:"el",g:["cattle","smallrum","equine"],kw:["χορτονομ","σανός","τριφύλλ"]},
  // Χειρισμός & περίφραξη
  {id:"J3ed7U5SRrA",c:"handle",t:"Εγκαταστάσεις & χειρισμός μικρού κοπαδιού προβάτων",ch:"OSU Extension",l:"en",g:["smallrum"],kw:["χειρισμ","διαλογ"]},
  {id:"BWGksusrdHs",c:"handle",t:"Εκτίμηση βάρους βοοειδών με μετροταινία",ch:"Purdue Extension",l:"en",g:["cattle"],kw:["βάρος","ζύγ"]},
  {id:"uTimrjgDa80",c:"handle",t:"Ηλεκτρική περίφραξη — πώς να την κάνουμε",ch:"Το Κανάλι του Γιάννη",l:"el",g:["all"],kw:["περίφραξ","βοσκ"]},
  {id:"hVmqE0tcV1Y",c:"handle",t:"Εντολές ποιμενικού σκύλου εξηγημένες",ch:"Seanthesheepman",l:"en",g:["dogs","smallrum"],kw:["σκύλ","βοσκ"]},
  // Πουλερικά
  {id:"7Zxl3jJjGlQ",c:"poultry",t:"Πώς να μεγαλώσετε κότες",ch:"Wikifarmer",l:"el",g:["poultry"],kw:["κοτέτσ","ωοτοκ","αυγ","φωτισμ"]},
  {id:"IRTf__2M7qg",c:"poultry",t:"Εκκόλαψη: πώς βγαίνει το κοτοπουλάκι στην κλωσσομηχανή",ch:"Farma Jim Cott",l:"el",g:["poultry"],kw:["επώαση","εκκόλαψ"]},
  {id:"LLdKVwSfcpc",c:"poultry",t:"Ωοσκόπηση αυγών",ch:"Farma Jim Cott",l:"el",g:["poultry"],kw:["ωοσκόπ","επώαση"]},
  {id:"NmvExuW2cM8",c:"poultry",t:"Θερμοκρασία κλωσσομητέρας & συμπεριφορά νεοσσών",ch:"Poulin Grain",l:"en",g:["poultry"],kw:["κλωσσομ","νεοσσ","θερμοκρασία θαλάμου"]},
  // Μελισσοκομία
  {id:"iF4yDHvj2eU",c:"bees",t:"Επιθεώρηση κυψέλης, αφεσμού & παραφυάδας",ch:"Μέλι Λεωνίδας",l:"el",g:["bees"],kw:["κυψέλ","σμηνουργ","παραφυάδ"]},
  {id:"cJZ1wc6Zwh0",c:"bees",t:"Σωστή τεχνική επιθεώρησης κυψέλης",ch:"UF Honey Bee Lab",l:"en",g:["bees"],kw:["κυψέλ","σμηνουργ"]},
  {id:"b8quxrkazSU",c:"bees",t:"Τρύγος μελιού στη Σίφνο",ch:"KAIPOUTHEOS.GR",l:"el",g:["bees"],kw:["τρύγ","μέλι"]},
  {id:"1iqfW_0EHVw",c:"bees",t:"Ξεκαπάκωμα κηρήθρας με ζεστό μαχαίρι",ch:"MahakoBees",l:"en",g:["bees"],kw:["τρύγ","ξεκαπάκ"]},
  {id:"3iQmbGNRO1w",c:"bees",t:"Θεραπεία βαρρόα με ενστάλαξη οξαλικού οξέος",ch:"To Kofini",l:"el",g:["bees"],kw:["βαρρόα","οξαλικ"]},
  {id:"k95CrnTSTCY",c:"bees",t:"Μέτρηση βαρρόα με πλύση αλκοόλης",ch:"University of Guelph",l:"en",g:["bees"],kw:["βαρρόα"]},
  // Εκτροφή ειδών
  {id:"-Gw-tScsU0U",c:"species",t:"Πώς γίνεται η εκτροφή σαλιγκαριών στην Ελλάδα",ch:"24h Online",l:"el",g:["snails"],kw:["σαλιγκ","πάρκ"]},
  {id:"UAIQszb7llU",c:"species",t:"Εκτροφή σαλιγκαριών",ch:"bioprasino.gr",l:"el",g:["snails"],kw:["σαλιγκ"]},
  {id:"12l15vLo_gk",c:"species",t:"Ιχθυοκαλλιέργεια πέστροφας — Άγκιστρο Σερρών",ch:"AGKISTRO ONLINE",l:"el",g:["fish"],kw:["πέστροφ","δεξαμεν"]},
  {id:"EUdUOF-Elm8",c:"species",t:"Πώς λειτουργεί μια σύγχρονη μονάδα πέστροφας",ch:"Aquaculture Tribe",l:"en",g:["fish"],kw:["πέστροφ","οξυγόν"]},
  {id:"XpHBWzhw5ec",c:"species",t:"Από τον μεταξοσκώληκα στο μετάξι — σηροτροφία στο Σουφλί",ch:"Smart Crochet",l:"el",g:["insects"],kw:["μεταξοσκ","κουκούλ"]},
  {id:"SFmwujBWBj4",c:"species",t:"Πώς εκτρέφουμε μεταξοσκώληκες",ch:"The More You Grow",l:"en",g:["insects"],kw:["μεταξοσκ"]},
  {id:"SbzedftrQJw",c:"species",t:"Μονάδα μαύρης στρατιωτικής μύγας (BSF)",ch:"Gardening Australia",l:"en",g:["insects"],kw:["bsf","έντομ","υπόστρωμ"]},
  {id:"GZU8Z5zlbZk",c:"species",t:"3 βασικά πράγματα στην εκτροφή κουνελιών",ch:"Φάρμα «Η Ράχη»",l:"el",g:["rabbit"],kw:["κουνέλ"]},
  {id:"MHdWsMdVMDA",c:"species",t:"Συζήτηση για τη χοιροτροφία",ch:"Σχολή Κρέατος",l:"el",g:["pig"],kw:["χοιρ"]},
  {id:"O4l0S0-1O4Y",c:"species",t:"Ελληνικός Ποιμενικός Σκύλος",ch:"Billy's Traffic TV (ΑΓΡΟweek)",l:"el",g:["dogs"],kw:["σκύλ","ποιμενικ"]},
  {id:"c7or0y2towI",c:"species",t:"Σκύλοι φύλακες προστατεύουν το κοπάδι από λύκους",ch:"BBC Earth",l:"en",g:["dogs","smallrum"],kw:["σκύλ","θηρευτ"]},
  {id:"3mWlTTDUHYY",c:"species",t:"Πώς να εκτρέψετε φασιανούς",ch:"Rambo Outfitters",l:"en",g:["poultry"],kw:["φασιαν"]},
  {id:"WuBEcjQ_2tk",c:"species",t:"Περιστέρια κρεατοπαραγωγής (πιτσούνια)",ch:"Sarah Chrisman",l:"en",g:["poultry"],kw:["περιστ","πιτσούν"]},
  {id:"e4vtz6dJR4U",c:"species",t:"Εκτροφή στρουθοκαμήλων — επίσκεψη σε φάρμα",ch:"Iowa PBS",l:"en",g:["poultry"],kw:["στρουθοκ"]},
  {id:"1T4QHdB8LK4",c:"species",t:"Μεγάλη μονάδα ελαφοτροφίας",ch:"Deer Farming Channel",l:"en",g:["game"],kw:["ελάφ","βαρβατίλ"]}
];

/* ================= ΠΕΡΙΣΣΟΤΕΡΑ ΕΛΛΗΝΙΚΑ ΒΙΝΤΕΟ (v1.5) ================= */
window.VIDEO_CATS.dairy="🧀 Γάλα & τυροκόμηση";
window.VIDEOS.push(
  // Περιποίηση
  {id:"dS2UWpAp7cA",c:"care",t:"Πώς κόβουμε σωστά τα νύχια στα πρόβατα",ch:"Farma Aggelopoulos",l:"el",g:["smallrum"],kw:["οπλ","νυχ","χωλότ","σήψη"]},
  {id:"CR_g1l_Nohg",c:"care",t:"Η κουρά των προβάτων στα Μητάτα",ch:"Eleni Lazarou",l:"el",g:["smallrum"],kw:["κούρεμα"]},
  // Υγεία
  {id:"ClL88f6FKB0",c:"health",t:"Έλεγχος υποκλινικής μαστίτιδας με CMT",ch:"PROUD Farm Incubator",l:"el",g:["cattle","smallrum"],kw:["μαστίτ","cmt","ξήρανση"]},
  {id:"iu05gtuh4O4",c:"health",t:"Ενημέρωση για τη νόσο «Ευλογιά των αιγοπροβάτων»",ch:"Περιφέρεια Στερεάς Ελλάδας",l:"el",g:["smallrum"],kw:["ευλογι","επαγρύπνηση","βιοασφάλ"]},
  {id:"6UJdRI5WQsM",c:"health",t:"Ευλογιά προβάτων: συμπτώματα & τι κάνει ο κτηνοτρόφος",ch:"ΕΡΤ Βορείου Αιγαίου",l:"el",g:["smallrum"],kw:["ευλογι","επαγρύπνηση"]},
  {id:"egpb816jhRo",c:"health",t:"Θερμικό στρες στις αγελάδες",ch:"Lagopoulos Farm",l:"el",g:["cattle"],kw:["θερμικ","καύσων"]},
  {id:"BzlP87C1guU",c:"health",t:"Πρόβλεψη θερμικού στρες στις αγελάδες",ch:"AlphaNews Live",l:"el",g:["cattle"],kw:["θερμικ","καύσων"]},
  {id:"FTsXy6ifCio",c:"health",t:"Ασφάλεια & υγεία κοτόπουλων",ch:"Wikifarmer",l:"el",g:["poultry"],kw:["βιοασφάλ","κοτέτσ","γρίπη","άκαρ"]},
  // Άμελξη
  {id:"t92BY1i9kd8",c:"milk",t:"Πώς & πότε να αρμέξετε την κατσίκα",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["άμελξ","γάλα"]},
  {id:"cMfj_efYH00",c:"milk",t:"Αίθουσα αρμεγής προβάτων υψηλής γραμμής — διαστασιολόγηση",ch:"NIK UTB",l:"el",g:["smallrum"],kw:["άμελξ","αμελκτήρ"]},
  {id:"_D_xHgxdYjo",c:"milk",t:"Παγίδα αρμέγματος στο αμελκτήριο",ch:"NIK UTB",l:"el",g:["smallrum"],kw:["άμελξ","αμελκτήρ"]},
  // Γάλα & τυροκόμηση
  {id:"BmM7ZFB25dg",c:"dairy",t:"Σπιτική τυροκόμηση φέτας στο Κουτσελιό Ιωαννίνων",ch:"Olga Krana",l:"el",g:["smallrum","cattle"],kw:["γάλα","τυρ"]},
  {id:"p6T_j7vfCpQ",c:"dairy",t:"Το τυρί στη Λήμνο: τυροκόμηση στο τυροκομείο",ch:"MedINA",l:"el",g:["smallrum","cattle"],kw:["γάλα","τυρ"]},
  {id:"R6fC4zSCQcc",c:"dairy",t:"Φτιάχνω ξινοτύρι (ξινομυζήθρα)",ch:"KostasSpear",l:"el",g:["smallrum","cattle"],kw:["γάλα","τυρ"]},
  // Τοκετός & νεογέννητα
  {id:"HDFVvoRaIT4",c:"birth",t:"Γέννα κατσίκας",ch:"Manos Milolidakis",l:"el",g:["smallrum"],kw:["τοκετ","γέννα"]},
  {id:"2gch-7PpVF0",c:"birth",t:"Τα νεογέννητα κατσικάκια",ch:"Dimis Farmer Stories",l:"el",g:["smallrum"],kw:["νεογέν","τοκετ"]},
  {id:"keFkI_n5eOQ",c:"birth",t:"Η αξία του πρωτογάλακτος στα νεογέννητα αρνιά",ch:"Heliades Farming Solutions",l:"el",g:["smallrum"],kw:["πρωτόγαλ","νεογέν"]},
  {id:"lqQPiuNkRzg",c:"birth",t:"Γέννα μοσχαριού",ch:"LifeEvents",l:"el",g:["cattle"],kw:["τοκετ","γέννα"]},
  // Αναπαραγωγή
  {id:"iufR6N2U984",c:"repro",t:"Τεχνητή σπερματέγχυση",ch:"PROUD Farm Incubator",l:"el",g:["cattle","smallrum"],kw:["σπερματέγχ","οίστρ"]},
  {id:"JD8PkLontLs",c:"repro",t:"Προετοιμασία κριών για τις οχείες",ch:"Αγγελίνα Κυριακοπούλου",l:"el",g:["smallrum"],kw:["οχεία","κριαρ","τράγ","flushing"]},
  // Διατροφή & χορτονομή
  {id:"j6RFHapIQfM",c:"feed",t:"Πώς να ταΐσετε τα πρόβατα",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["σιτηρέσ","ζωοτροφ","διατροφ","βοσκ","συμπλήρωμα"]},
  {id:"Wt_WAEI-vlg",c:"feed",t:"Πώς να ταΐσετε τις κατσίκες",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["σιτηρέσ","ζωοτροφ","διατροφ","βοσκ"]},
  {id:"PsgaSsz69D0",c:"feed",t:"Διατροφή αγροτικών ζώων — βασικές αρχές, σιτηρέσιο",ch:"Innovation and Impact Hub",l:"el",g:["smallrum","cattle"],kw:["σιτηρέσ","ζωοτροφ","διατροφ"]},
  {id:"6c7i6-xKk_w",c:"feed",t:"Πρόβατα Ασσάφ: διατροφή & ποιότητα γάλακτος",ch:"Farma Hellas Genetics",l:"el",g:["smallrum"],kw:["σιτηρέσ","διατροφ","γάλα"]},
  {id:"1xHITRsKK3Y",c:"feed",t:"Σύγχρονη διατροφή & διαχείριση προβάτων Lacaune (σεμινάριο)",ch:"ΒΙΟΖΩΚΑΤ",l:"el",g:["smallrum"],kw:["σιτηρέσ","διατροφ","μετάβασ"]},
  {id:"aBD0gC27gU8",c:"feed",t:"Διατροφή & διαχείριση αιγοπροβάτων υψηλής γαλακτοπαραγωγής",ch:"ΒΙΟΖΩΚΑΤ (Zootechnia 2023)",l:"el",g:["smallrum"],kw:["σιτηρέσ","διατροφ","τοξαιμ"]},
  {id:"BKCIi37Me_E",c:"feed",t:"Κατάρτιση σιτηρεσίων αγελάδων γαλακτοπαραγωγής",ch:"Optimal Diet FS",l:"el",g:["cattle"],kw:["σιτηρέσ","διατροφ","μετάβασ","close-up"]},
  {id:"VPVKoDdbnEk",c:"feed",t:"Υγεία γαστρεντερικού των γαλακτοπαραγωγών αγελάδων (σεμινάριο)",ch:"ΒΙΟΖΩΚΑΤ",l:"el",g:["cattle"],kw:["οξέωση","σιτηρέσ","διατροφ"]},
  {id:"nj8Ei6o_5ag",c:"feed",t:"Ενσίρωση μηδικής (τριφύλλι)",ch:"Agro 83 GR",l:"el",g:["cattle","smallrum"],kw:["ενσίρωμα","ενσίρωση","τριφύλλ"]},
  {id:"Hgp8EQma8nU",c:"feed",t:"Ενσίρωση μηδικής — όλη η διαδικασία",ch:"Savvas Kefalas",l:"el",g:["cattle","smallrum"],kw:["ενσίρωμα","ενσίρωση","χορτονομ"]},
  // Χειρισμός, εγκαταστάσεις & περίφραξη
  {id:"UH5DxZZmTWI",c:"handle",t:"Υποστατικά αιγοπροβάτων",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["smallrum"],kw:["σταβλ","υποστατ","χειρισμ","αερισμ"]},
  {id:"JGPXByZ8FVc",c:"handle",t:"Σύγχρονη τεχνολογία στις μονάδες αγελαδοτροφίας",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["cattle"],kw:["σταβλ","άμελξ","τεχνολογ"]},
  {id:"f_HSfCqNGnk",c:"handle",t:"Ηλεκτρικός φράχτης για προστασία των οικόσιτων ζώων",ch:"Έξυπνο αγρόκτημα",l:"el",g:["all"],kw:["περίφραξ","θηρευτ"]},
  {id:"SA1tRri-5II",c:"handle",t:"Ελληνικά ποιμενικά κουτάβια: εκπαίδευση & μεγάλωμα",ch:"ΛΥΚΟΜΑΧΙΝ",l:"el",g:["dogs"],kw:["σκύλ","ποιμενικ"]},
  // Πουλερικά
  {id:"F9HJv6edpe8",c:"poultry",t:"Κοτέτσι εύκολο στην κατασκευή",ch:"Το Κανάλι του Γιάννη",l:"el",g:["poultry"],kw:["κοτέτσ","φωλι"]},
  {id:"6S4Vsa_f-MI",c:"poultry",t:"Θερμομάνα για νεοσσούς: τι πρέπει να προσέξω",ch:"KOTES.GR",l:"el",g:["poultry"],kw:["κλωσσομ","νεοσσ","θερμοκρασία θαλάμου"]},
  {id:"zTXGk4yqQX8",c:"poultry",t:"Χρήσιμες πληροφορίες για επιτυχημένη εκκόλαψη",ch:"Farma Jim Cott",l:"el",g:["poultry"],kw:["επώαση","εκκόλαψ"]},
  {id:"9SQTZN_JP8o",c:"poultry",t:"5 λάθη στην εκτροφή των ορτυκιών",ch:"Φάρμα «Η Ράχη»",l:"el",g:["poultry"],kw:["ορτύκ"]},
  {id:"rahXXnxJJs4",c:"poultry",t:"Πληροφορίες για τις πάπιες της φάρμας",ch:"Φάρμα «Η Ράχη»",l:"el",g:["poultry"],kw:["πάπι"]},
  {id:"KqOh4fRutDg",c:"poultry",t:"Πάπια Βαρβαρίας (Cairina moschata)",ch:"Φάρμα «Η Ράχη»",l:"el",g:["poultry"],kw:["πάπι"]},
  {id:"ISWNzLmbvW4",c:"poultry",t:"Γαλοπουλάκια τις πρώτες μέρες",ch:"Το Κανάλι του Γιάννη",l:"el",g:["poultry"],kw:["γαλοπ","νεοσσ"]},
  {id:"IlIYVtiXEUw",c:"poultry",t:"Το σωστό κλουβί για τους φασιανούς",ch:"Φάρμα πτηνών Peristeras P3",l:"el",g:["poultry"],kw:["φασιαν"]},
  {id:"FS6PcCI2lVQ",c:"poultry",t:"Φασιανοί & πέρδικες στο εκτροφείο θηραμάτων Νάουσας",ch:"vDimitris",l:"el",g:["poultry"],kw:["φασιαν","πέρδικ","θηραμ"]},
  {id:"AJ1g8B0pAE0",c:"poultry",t:"Εκτροφείο θηραμάτων Κυνηγετικού Συλλόγου Βόλου",ch:"Kynigesia",l:"el",g:["poultry"],kw:["πέρδικ","φασιαν","θηραμ"]},
  {id:"vjL0901tZqo",c:"poultry",t:"Νησιώτικες πέρδικες (Alectoris chukar)",ch:"Φάρμα «Η Ράχη»",l:"el",g:["poultry"],kw:["πέρδικ"]},
  {id:"4LiePtPGL9Y",c:"poultry",t:"Η πρώτη φάρμα στρουθοκαμήλων στην Ελλάδα",ch:"ΕΡΤ",l:"el",g:["poultry"],kw:["στρουθοκ"]},
  // Μελισσοκομία
  {id:"u6BaDdu2Apg",c:"bees",t:"Μελισσοκομία για αρχάριους, βήμα-βήμα",ch:"Ορεινή Μέλισσα",l:"el",g:["bees"],kw:["κυψέλ","μελίσσ"]},
  {id:"LXx2ekM2psk",c:"bees",t:"Πρακτικό σεμινάριο για αρχάριους μελισσοκόμους",ch:"EllinikoMeli",l:"el",g:["bees"],kw:["κυψέλ","μελίσσ"]},
  {id:"yV56TLaICxc",c:"bees",t:"Παραφυάδες χωρίς βασιλοτροφία & χωρίς μετακίνηση",ch:"Ορεινή Μέλισσα",l:"el",g:["bees"],kw:["παραφυάδ","σμηνουργ"]},
  {id:"uEJXqwfPrRw",c:"bees",t:"Μέθοδος Ντεμαρί για πρόληψη της σμηνουργίας",ch:"Δυτική Μέλισσα",l:"el",g:["bees"],kw:["σμηνουργ"]},
  {id:"Xf1Rl8ffR3A",c:"bees",t:"Τροφοδοσία μελισσών: πότε, πόσο, τι & γιατί",ch:"Στέργιος Στεργάτος",l:"el",g:["bees"],kw:["διέγερση","τροφ","σιρόπ","αποθεμ"]},
  {id:"VZ9xRKRDums",c:"bees",t:"Κανόνες εισαγωγής βασίλισσας για 100% αποδοχή",ch:"melistalaktos.gr",l:"el",g:["bees"],kw:["βασίλισσ","παραφυάδ"]},
  {id:"MOAOLZ2sEkM",c:"bees",t:"Οξαλικό οξύ με εξάχνωση κατά της βαρρόα",ch:"Ορεινό Μέλι",l:"el",g:["bees"],kw:["βαρρόα","οξαλικ"]},
  {id:"BgB5UShYPCY",c:"bees",t:"Έλεγχος βαρρόα μετά από οξαλικό & αμιτράζ",ch:"Rhodian bees",l:"el",g:["bees"],kw:["βαρρόα"]},
  {id:"z8n4Oq1k5M8",c:"bees",t:"Τρύγος ανθόμελου από παραφυάδες",ch:"Μελισσοκομία Melefsis",l:"el",g:["bees"],kw:["τρύγ","μέλι"]},
  {id:"bNO13uvRB_M",c:"bees",t:"Νέος μελισσοκόμος — οικογενειακή επιχείρηση",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["bees"],kw:["μελίσσ"]},
  // Εκτροφή ειδών
  {id:"eG_70lF72js",c:"species",t:"Πώς να μεγαλώσετε πρόβατα",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["πρόβατ"]},
  {id:"oweQj3w5dZw",c:"species",t:"Πώς να μεγαλώσω κατσίκες",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["κατσίκ","αίγ"]},
  {id:"FzCUTy7PweM",c:"species",t:"Πώς να φροντίσετε τις κατσίκες",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["κατσίκ","αίγ"]},
  {id:"QUvfSqlDFww",c:"species",t:"Πώς να επιλέξετε κατσίκια για γάλα & για κρέας",ch:"Wikifarmer",l:"el",g:["smallrum"],kw:["κατσίκ","φυλ"]},
  {id:"eAlmu2AJsfQ",c:"species",t:"Αιγοπροβατοτρόφος — οικογενειακή επιχείρηση",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["smallrum"],kw:["πρόβατ"]},
  {id:"AwqxQfYrBVs",c:"species",t:"Αγελαδοτρόφος — οικογενειακή επιχείρηση",ch:"Τμήμα Γεωργίας Κύπρου",l:"el",g:["cattle"],kw:["αγελάδ"]},
  {id:"QiNNqeDD_0Y",c:"species",t:"Η αγελαδοτροφία στην Ελλάδα",ch:"Dimis Farmer Stories",l:"el",g:["cattle"],kw:["αγελάδ"]},
  {id:"3cBtGSXI9KQ",c:"species",t:"Φάρμα Γκαντζώρα — εκτροφή βοοειδών",ch:"Dimis Farmer Stories",l:"el",g:["cattle"],kw:["μοσχάρ","βοοειδ","πάχυνση"]},
  {id:"MgOpDvn86Bc",c:"species",t:"Σε τι υπερέχει το καραγκούνικο πρόβατο",ch:"ΕΡΤ",l:"el",g:["smallrum"],kw:["καραγκούν","φυλ"]},
  {id:"t3CIVy41k0g",c:"species",t:"Η σπάνια φυλή προβάτων Φλώρινας-Πελαγονίας",ch:"ΕΡΤ",l:"el",g:["smallrum"],kw:["φλώριν","φυλ"]},
  {id:"hQwNb39RWM8",c:"species",t:"Το χιώτικο πρόβατο (Διευθυντής Κτηνιατρείου Χίου)",ch:"Alithia MME",l:"el",g:["smallrum"],kw:["χιώτικ","φυλ"]},
  {id:"qxaY4L6b4aM",c:"species",t:"Γίδια Σκοπέλου — μια σπάνια φυλή αιγών",ch:"Dimis Farmer Stories",l:"el",g:["smallrum"],kw:["σκοπέλ","φυλ"]},
  {id:"6Wy_SQBMfwQ",c:"species",t:"Αυτόχθονες φυλές αιγοπροβάτων (Gen Sheep Milk)",ch:"Innovation and Impact Hub",l:"el",g:["smallrum"],kw:["φυλ","αυτόχθον"]},
  {id:"DrRK7XRx0Pw",c:"species",t:"Τα βουβάλια της Κερκίνης χρειάζονται νερό & δροσιά",ch:"alterthess",l:"el",g:["cattle"],kw:["βουβάλ","θερμικ"]},
  {id:"vlxa-plk2rY",c:"species",t:"Φάρμα βουβαλιών — λίμνη Κερκίνη",ch:"Agro 83 GR",l:"el",g:["cattle"],kw:["βουβάλ"]},
  {id:"P4PMux2oSAM",c:"species",t:"Μαύρος χοίρος — από το χωράφι στο ράφι",ch:"ΕΡΤ",l:"el",g:["pig"],kw:["χοιρ"]},
  {id:"WZchKE12Xzc",c:"species",t:"Μαύρος χοίρος — συνεργασία ΕΚΕΤΑ με φάρμα",ch:"Fotiadis Farm",l:"el",g:["pig"],kw:["χοιρ"]},
  {id:"hvOexnyoV54",c:"species",t:"Ελάφια πλατώνια (ντάμα-ντάμα) — Κοζάνη",ch:"Ελληνικό Κέντρο Παρατήρησης",l:"el",g:["game"],kw:["ελάφ"]},
  {id:"RfRJ9ItZlhs",c:"species",t:"Η μοναδική φάρμα με ελάφια στην Κύπρο",ch:"AlphaNews Live",l:"el",g:["game"],kw:["ελάφ"]},
  {id:"3jTwLNWLn9Y",c:"species",t:"Μονάδα παραγωγής αγριογούρουνων",ch:"TV100 Θεσσαλονίκη",l:"el",g:["game"],kw:["αγριόχ","αγριογούρ"]},
  {id:"4HkvxHmBY6E",c:"species",t:"Η τέχνη του πεταλωτή",ch:"ΕΡΤ",l:"el",g:["equine"],kw:["πεταλ","οπλ"]},
  {id:"5_a1fM6_guM",c:"species",t:"Πετάλωμα αλόγων με τον Δημήτρη Μανάβη",ch:"Εμπρός Επικοινωνία Αιγαίου",l:"el",g:["equine"],kw:["πεταλ","οπλ"]},
  {id:"pF43cF9z_IE",c:"species",t:"Φάρμα με γαϊδουράκια στην Οινόη Κοζάνης",ch:"ΕΡΤ",l:"el",g:["equine"],kw:["γαϊδ"]},
  {id:"EXQHJeoKbUI",c:"species",t:"Τι να δίνουμε στα κουνέλια",ch:"Andreas Papastefanakis",l:"el",g:["rabbit"],kw:["κουνέλ","τροφ"]},
  {id:"lPyGesqTVLk",c:"species",t:"Η αναπαραγωγή των κουνελιών",ch:"FARMA A7",l:"el",g:["rabbit"],kw:["κουνέλ","αναπαραγ"]},
  {id:"z6hdohKkkNI",c:"species",t:"Η πρώτη μονάδα εκτροφής πέστροφας στην ορεινή Ροδόπη",ch:"ERT3",l:"el",g:["fish"],kw:["πέστροφ"]},
  {id:"c9bD4LL1Q88",c:"species",t:"Σουφλί: εκτροφή μεταξοσκώληκα",ch:"OPEN",l:"el",g:["insects"],kw:["μεταξοσκ"]}
);
